/*
 Copyright 2009-2017 Kris Kowal under the terms of the MIT
 license found at https://github.com/kriskowal/q/blob/v1/LICENSE

 With parts by Tyler Close
 Copyright 2007-2009 Tyler Close under the terms of the MIT X license found
 at http://www.opensource.org/licenses/mit-license.html
 Forked at ref_send.js version: 2009-05-11

 With parts by Mark Miller
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

*/
(function(f){if("function"===typeof bootstrap)bootstrap("promise",f);else if("object"===typeof exports&&"object"===typeof module)module.exports=f();else if("function"===typeof define&&define.amd)define(f);else if("undefined"!==typeof ses)ses.ok()&&(ses.makeQ=f);else if("undefined"!==typeof window||"undefined"!==typeof self){var n="undefined"!==typeof window?window:self,x=n.Q;n.Q=f();n.Q.noConflict=function(){n.Q=x;return this}}else throw Error("This environment was not anticipated by Q. Please file a bug.");
})(function(){function f(b){return function(){return m.apply(b,arguments)}}function n(b,e){if(aa&&e.stack&&"object"===typeof b&&null!==b&&b.stack){for(var c=[],t=e;t;t=t.source)t.stack&&(!b.__minimumStackCounter__||b.__minimumStackCounter__>t.stackCounter)&&(Ia(b,"__minimumStackCounter__",{value:t.stackCounter,configurable:!0}),c.unshift(t.stack));c.unshift(b.stack);c=c.join("\nFrom previous event:\n").split("\n");t=[];for(var f=0;f<c.length;++f){var g=c[f],C;if(C=x(g)){var k=C[1];C=C[0]===ka&&k>=
    ba&&k<=Ja}else C=!1;C||(C=g,C=-1!==C.indexOf("(module.js:")||-1!==C.indexOf("(node.js:"));C||!g||t.push(g)}c=t.join("\n");Ia(b,"stack",{value:c,configurable:!0})}}function x(b){var e=/at .+ \((.+):(\d+):(?:\d+)\)$/.exec(b);if(e||(e=/at ([^ ]+):(\d+):(?:\d+)$/.exec(b)))return[e[1],Number(e[2])];if(b=/.*@(.+):(\d+)$/.exec(b))return[b[1],Number(b[2])]}function A(){if(aa)try{throw Error();}catch(e){var b=e.stack.split("\n");b=0<b[0].indexOf("@")?b[1]:b[2];if(b=x(b))return ka=b[0],b[1]}}function c(b){return b instanceof
g?b:E(b)?la(b):U(b)}function r(){function b(b){t=b;c.longStackSupport&&aa&&(M.source=b);ma(e,function(e,l){c.nextTick(function(){b.promiseDispatch.apply(b,l)})},void 0);l=e=void 0}var e=[],l=[],t,f=k(r.prototype),M=k(g.prototype);M.promiseDispatch=function(b,f,g){var C=z(arguments);e?(e.push(C),"when"===f&&g[1]&&l.push(g[1])):c.nextTick(function(){t.promiseDispatch.apply(t,C)})};M.valueOf=function(){if(e)return M;var b=wa(t);J(b)&&(t=b);return b};M.inspect=function(){return t?t.inspect():{state:"pending"}};
    if(c.longStackSupport&&aa)try{throw Error();}catch(C){M.stack=C.stack.substring(C.stack.indexOf("\n")+1),M.stackCounter=Ka++}f.promise=M;f.resolve=function(e){t||b(c(e))};f.fulfill=function(e){t||b(U(e))};f.reject=function(e){t||b(F(e))};f.notify=function(b){t||ma(l,function(e,l){c.nextTick(function(){l(b)})},void 0)};return f}function K(b){if("function"!==typeof b)throw new TypeError("resolver must be a function.");var e=r();try{b(e.resolve,e.reject,e.notify)}catch(l){e.reject(l)}return e.promise}
    function p(b){return K(function(e,l){for(var f=0,g=b.length;f<g;f++)c(b[f]).then(e,l)})}function g(b,e,c){void 0===e&&(e=function(b){return F(Error("Promise does not support operation: "+b))});void 0===c&&(c=function(){return{state:"unknown"}});var l=k(g.prototype);l.promiseDispatch=function(c,f,t){try{var g=b[f]?b[f].apply(l,t):e.call(l,f,t)}catch(ca){g=F(ca)}c&&c(g)};if(l.inspect=c){var f=c();"rejected"===f.state&&(l.exception=f.reason);l.valueOf=function(){var b=c();return"pending"===b.state||
    "rejected"===b.state?l:b.value}}return l}function y(b,e,l,f){return c(b).then(e,l,f)}function wa(b){if(J(b)){var e=b.inspect();if("fulfilled"===e.state)return e.value}return b}function J(b){return b instanceof g}function E(b){return b===Object(b)&&"function"===typeof b.then}function G(){V.length=0;W.length=0;L||(L=!0)}function v(b,e){L&&("object"===typeof process&&"function"===typeof process.emit&&c.nextTick.runAfter(function(){-1!==oa(W,b)&&(process.emit("unhandledRejection",e,b),xa.push(b))}),W.push(b),
        e&&"undefined"!==typeof e.stack?V.push(e.stack):V.push("(no stack) "+e))}function La(b){if(L){var e=oa(W,b);-1!==e&&("object"===typeof process&&"function"===typeof process.emit&&c.nextTick.runAfter(function(){var c=oa(xa,b);-1!==c&&(process.emit("rejectionHandled",V[e],b),xa.splice(c,1))}),W.splice(e,1),V.splice(e,1))}}function F(b){var e=g({when:function(e){e&&La(this);return e?e(b):this}},function(){return this},function(){return{state:"rejected",reason:b}});v(e,b);return e}function U(b){return g({when:function(){return b},
        get:function(e){return b[e]},set:function(e,c){b[e]=c},"delete":function(e){delete b[e]},post:function(e,c){return null===e||void 0===e?b.apply(void 0,c):b[e].apply(b,c)},apply:function(e,c){return b.apply(e,c)},keys:function(){return D(b)}},void 0,function(){return{state:"fulfilled",value:b}})}function la(b){var e=r();c.nextTick(function(){try{b.then(e.resolve,e.reject,e.notify)}catch(l){e.reject(l)}});return e.promise}function X(b,e,l){return c(b).spread(e,l)}function Ca(b,e,l){return c(b).dispatch(e,
        l)}function N(b){return y(b,function(b){var e=0,c=r();ma(b,function(l,f,g){var t;J(f)&&"fulfilled"===(t=f.inspect()).state?b[g]=t.value:(++e,y(f,function(l){b[g]=l;0===--e&&c.resolve(b)},c.reject,function(b){c.notify({index:g,value:b})}))},void 0);0===e&&c.resolve(b);return c.promise})}function H(b){if(0===b.length)return c.resolve();var e=c.defer(),l=0;ma(b,function(c,f,g){c=b[g];l++;y(c,function(b){e.resolve(b)},function(b){l--;0===l&&(b=b||Error(""+b),b.message="Q can't get fulfillment value from any promise, all promises were rejected. Last error message: "+
        b.message,e.reject(b))},function(b){e.notify({index:g,value:b})})},void 0);return e.promise}function O(b){return y(b,function(b){b=ya(b,c);return y(N(ya(b,function(b){return y(b,Da,Da)})),function(){return b})})}var aa=!1;try{throw Error();}catch(b){aa=!!b.stack}var ba=A(),ka,Da=function(){},da=function(){function b(){for(var b,l;c.next;){c=c.next;b=c.task;c.task=void 0;if(l=c.domain)c.domain=void 0,l.enter();e(b,l)}for(;n.length;)b=n.pop(),e(b);g=!1}function e(e,c){try{e()}catch(w){if(m)throw c&&
    c.exit(),setTimeout(b,0),c&&c.enter(),w;setTimeout(function(){throw w;},0)}c&&c.exit()}var c={task:void 0,next:null},f=c,g=!1,k=void 0,m=!1,n=[];da=function(b){f=f.next={task:b,domain:m&&process.domain,next:null};g||(g=!0,k())};if("object"===typeof process&&"[object process]"===process.toString()&&process.nextTick)m=!0,k=function(){process.nextTick(b)};else if("function"===typeof setImmediate)k="undefined"!==typeof window?setImmediate.bind(window,b):function(){setImmediate(b)};else if("undefined"!==
        typeof MessageChannel){var r=new MessageChannel;r.port1.onmessage=function(){k=p;r.port1.onmessage=b;b()};var p=function(){r.port2.postMessage(0)};k=function(){setTimeout(b,0);p()}}else k=function(){setTimeout(b,0)};da.runAfter=function(b){n.push(b);g||(g=!0,k())};return da}(),m=Function.call,z=f(Array.prototype.slice),ma=f(Array.prototype.reduce||function(b,e){var c=0,f=this.length;if(1===arguments.length){do{if(c in this){e=this[c++];break}if(++c>=f)throw new TypeError;}while(1)}for(;c<f;c++)c in
    this&&(e=b(e,this[c],c));return e}),oa=f(Array.prototype.indexOf||function(b){for(var e=0;e<this.length;e++)if(this[e]===b)return e;return-1}),ya=f(Array.prototype.map||function(b,e){var c=this,f=[];ma(c,function(l,g,k){f.push(b.call(e,g,k,c))},void 0);return f}),k=Object.create||function(b){function e(){}e.prototype=b;return new e},Ia=Object.defineProperty||function(b,e,c){b[e]=c.value;return b},Ya=f(Object.prototype.hasOwnProperty),D=Object.keys||function(b){var e=[],c;for(c in b)Ya(b,c)&&e.push(c);
        return e},pa=f(Object.prototype.toString);var za="undefined"!==typeof ReturnValue?ReturnValue:function(b){this.value=b};c.resolve=c;c.nextTick=da;c.longStackSupport=!1;var Ka=1;"object"===typeof process&&process&&process.env&&process.env.Q_DEBUG&&(c.longStackSupport=!0);c.defer=r;r.prototype.makeNodeResolver=function(){var b=this;return function(e,c){e?b.reject(e):2<arguments.length?b.resolve(z(arguments,1)):b.resolve(c)}};c.Promise=K;c.promise=K;K.race=p;K.all=N;K.reject=F;K.resolve=c;c.passByCopy=
        function(b){return b};g.prototype.passByCopy=function(){return this};c.join=function(b,e){return c(b).join(e)};g.prototype.join=function(b){return c([this,b]).spread(function(b,c){if(b===c)return b;throw Error("Q can't join: not the same: "+b+" "+c);})};c.race=p;g.prototype.race=function(){return this.then(c.race)};c.makePromise=g;g.prototype.toString=function(){return"[object Promise]"};g.prototype.then=function(b,e,f){function l(c){try{return"function"===typeof b?b(c):c}catch(ca){return F(ca)}}
        function g(b){if("function"===typeof e){n(b,k);try{return e(b)}catch(ca){return F(ca)}}return F(b)}var k=this,m=r(),p=!1;c.nextTick(function(){k.promiseDispatch(function(b){p||(p=!0,m.resolve(l(b)))},"when",[function(b){p||(p=!0,m.resolve(g(b)))}])});k.promiseDispatch(void 0,"when",[void 0,function(b){var e=!1;try{var l="function"===typeof f?f(b):b}catch(Ea){if(e=!0,c.onerror)c.onerror(Ea);else throw Ea;}e||m.notify(l)}]);return m.promise};c.tap=function(b,e){return c(b).tap(e)};g.prototype.tap=function(b){b=
        c(b);return this.then(function(c){return b.fcall(c).thenResolve(c)})};c.when=y;g.prototype.thenResolve=function(b){return this.then(function(){return b})};c.thenResolve=function(b,e){return c(b).thenResolve(e)};g.prototype.thenReject=function(b){return this.then(function(){throw b;})};c.thenReject=function(b,e){return c(b).thenReject(e)};c.nearer=wa;c.isPromise=J;c.isPromiseAlike=E;c.isPending=function(b){return J(b)&&"pending"===b.inspect().state};g.prototype.isPending=function(){return"pending"===
        this.inspect().state};c.isFulfilled=function(b){return!J(b)||"fulfilled"===b.inspect().state};g.prototype.isFulfilled=function(){return"fulfilled"===this.inspect().state};c.isRejected=function(b){return J(b)&&"rejected"===b.inspect().state};g.prototype.isRejected=function(){return"rejected"===this.inspect().state};var V=[],W=[],xa=[],L=!0;c.resetUnhandledRejections=G;c.getUnhandledReasons=function(){return V.slice()};c.stopUnhandledRejectionTracking=function(){G();L=!1};G();c.reject=F;c.fulfill=U;
    c.master=function(b){return g({isDef:function(){}},function(c,f){return Ca(b,c,f)},function(){return c(b).inspect()})};c.spread=X;g.prototype.spread=function(b,c){return this.all().then(function(c){return b.apply(void 0,c)},c)};c.async=function(b){return function(){function e(b,e){if("undefined"===typeof StopIteration){try{var l=f[b](e)}catch(na){return F(na)}return l.done?c(l.value):y(l.value,g,k)}try{l=f[b](e)}catch(na){return l=na,"[object StopIteration]"===pa(l)||l instanceof za?c(na.value):F(na)}return y(l,
        g,k)}var f=b.apply(this,arguments),g=e.bind(e,"next"),k=e.bind(e,"throw");return g()}};c.spawn=function(b){c.done(c.async(b)())};c["return"]=function(b){throw new za(b);};c.promised=function(b){return function(){return X([this,N(arguments)],function(c,f){return b.apply(c,f)})}};c.dispatch=Ca;g.prototype.dispatch=function(b,e){var f=this,g=r();c.nextTick(function(){f.promiseDispatch(g.resolve,b,e)});return g.promise};c.get=function(b,e){return c(b).dispatch("get",[e])};g.prototype.get=function(b){return this.dispatch("get",
        [b])};c.set=function(b,e,f){return c(b).dispatch("set",[e,f])};g.prototype.set=function(b,c){return this.dispatch("set",[b,c])};c.del=c["delete"]=function(b,e){return c(b).dispatch("delete",[e])};g.prototype.del=g.prototype["delete"]=function(b){return this.dispatch("delete",[b])};c.mapply=c.post=function(b,e,f){return c(b).dispatch("post",[e,f])};g.prototype.mapply=g.prototype.post=function(b,c){return this.dispatch("post",[b,c])};c.send=c.mcall=c.invoke=function(b,e){return c(b).dispatch("post",
        [e,z(arguments,2)])};g.prototype.send=g.prototype.mcall=g.prototype.invoke=function(b){return this.dispatch("post",[b,z(arguments,1)])};c.fapply=function(b,e){return c(b).dispatch("apply",[void 0,e])};g.prototype.fapply=function(b){return this.dispatch("apply",[void 0,b])};c["try"]=c.fcall=function(b){return c(b).dispatch("apply",[void 0,z(arguments,1)])};g.prototype.fcall=function(){return this.dispatch("apply",[void 0,z(arguments)])};c.fbind=function(b){var e=c(b),f=z(arguments,1);return function(){return e.dispatch("apply",
        [this,f.concat(z(arguments))])}};g.prototype.fbind=function(){var b=this,c=z(arguments);return function(){return b.dispatch("apply",[this,c.concat(z(arguments))])}};c.keys=function(b){return c(b).dispatch("keys",[])};g.prototype.keys=function(){return this.dispatch("keys",[])};c.all=N;g.prototype.all=function(){return N(this)};c.any=H;g.prototype.any=function(){return H(this)};c.allResolved=function(b,c,f){return function(){"undefined"!==typeof console&&"function"===typeof console.warn&&console.warn(c+
        " is deprecated, use "+f+" instead.",Error("").stack);return b.apply(b,arguments)}}(O,"allResolved","allSettled");g.prototype.allResolved=function(){return O(this)};c.allSettled=function(b){return c(b).allSettled()};g.prototype.allSettled=function(){return this.then(function(b){return N(ya(b,function(b){function e(){return b.inspect()}b=c(b);return b.then(e,e)}))})};c.fail=c["catch"]=function(b,e){return c(b).then(void 0,e)};g.prototype.fail=g.prototype["catch"]=function(b){return this.then(void 0,
        b)};c.progress=function(b,e){return c(b).then(void 0,void 0,e)};g.prototype.progress=function(b){return this.then(void 0,void 0,b)};c.fin=c["finally"]=function(b,e){return c(b)["finally"](e)};g.prototype.fin=g.prototype["finally"]=function(b){if(!b||"function"!==typeof b.apply)throw Error("Q can't apply finally callback");b=c(b);return this.then(function(c){return b.fcall().then(function(){return c})},function(c){return b.fcall().then(function(){throw c;})})};c.done=function(b,e,f,g){return c(b).done(e,
        f,g)};g.prototype.done=function(b,e,f){var g=function(b){c.nextTick(function(){n(b,l);if(c.onerror)c.onerror(b);else throw b;})},l=b||e||f?this.then(b,e,f):this;"object"===typeof process&&process&&process.domain&&(g=process.domain.bind(g));l.then(void 0,g)};c.timeout=function(b,e,f){return c(b).timeout(e,f)};g.prototype.timeout=function(b,c){var e=r(),f=setTimeout(function(){c&&"string"!==typeof c||(c=Error(c||"Timed out after "+b+" ms"),c.code="ETIMEDOUT");e.reject(c)},b);this.then(function(b){clearTimeout(f);
        e.resolve(b)},function(b){clearTimeout(f);e.reject(b)},e.notify);return e.promise};c.delay=function(b,e){void 0===e&&(e=b,b=void 0);return c(b).delay(e)};g.prototype.delay=function(b){return this.then(function(c){var e=r();setTimeout(function(){e.resolve(c)},b);return e.promise})};c.nfapply=function(b,e){return c(b).nfapply(e)};g.prototype.nfapply=function(b){var c=r();b=z(b);b.push(c.makeNodeResolver());this.fapply(b).fail(c.reject);return c.promise};c.nfcall=function(b){var e=z(arguments,1);return c(b).nfapply(e)};
    g.prototype.nfcall=function(){var b=z(arguments),c=r();b.push(c.makeNodeResolver());this.fapply(b).fail(c.reject);return c.promise};c.nfbind=c.denodeify=function(b){if(void 0===b)throw Error("Q can't wrap an undefined function");var e=z(arguments,1);return function(){var f=e.concat(z(arguments)),g=r();f.push(g.makeNodeResolver());c(b).fapply(f).fail(g.reject);return g.promise}};g.prototype.nfbind=g.prototype.denodeify=function(){var b=z(arguments);b.unshift(this);return c.denodeify.apply(void 0,b)};
    c.nbind=function(b,e){var f=z(arguments,2);return function(){var g=f.concat(z(arguments)),k=r();g.push(k.makeNodeResolver());c(function(){return b.apply(e,arguments)}).fapply(g).fail(k.reject);return k.promise}};g.prototype.nbind=function(){var b=z(arguments,0);b.unshift(this);return c.nbind.apply(void 0,b)};c.nmapply=c.npost=function(b,e,f){return c(b).npost(e,f)};g.prototype.nmapply=g.prototype.npost=function(b,c){var e=z(c||[]),f=r();e.push(f.makeNodeResolver());this.dispatch("post",[b,e]).fail(f.reject);
        return f.promise};c.nsend=c.nmcall=c.ninvoke=function(b,e){var f=z(arguments,2),g=r();f.push(g.makeNodeResolver());c(b).dispatch("post",[e,f]).fail(g.reject);return g.promise};g.prototype.nsend=g.prototype.nmcall=g.prototype.ninvoke=function(b){var c=z(arguments,1),f=r();c.push(f.makeNodeResolver());this.dispatch("post",[b,c]).fail(f.reject);return f.promise};c.nodeify=function(b,e){return c(b).nodeify(e)};g.prototype.nodeify=function(b){if(b)this.then(function(e){c.nextTick(function(){b(null,e)})},
        function(e){c.nextTick(function(){b(e)})});else return this};c.noConflict=function(){throw Error("Q.noConflict only works when Q is used as a global");};var Ja=A();return c});
(function(f,n){"object"===typeof exports&&"undefined"!==typeof module?module.exports=n():"function"===typeof define&&define.amd?define(n):f.moment=n()})(this,function(){function f(){return Jb.apply(null,arguments)}function n(a){return"[object Array]"===Object.prototype.toString.call(a)}function x(a){return a instanceof Date||"[object Date]"===Object.prototype.toString.call(a)}function A(a,d){var b=[],c;for(c=0;c<a.length;++c)b.push(d(a[c],c));return b}function c(a,d){return Object.prototype.hasOwnProperty.call(a,
    d)}function r(a,d){for(var b in d)c(d,b)&&(a[b]=d[b]);c(d,"toString")&&(a.toString=d.toString);c(d,"valueOf")&&(a.valueOf=d.valueOf);return a}function K(a,d,b,c){return Ea(a,d,b,c,!0).utc()}function p(a){null==a._pf&&(a._pf={empty:!1,unusedTokens:[],unusedInput:[],overflow:-2,charsLeftOver:0,nullInput:!1,invalidMonth:null,invalidFormat:!1,userInvalidated:!1,iso:!1});return a._pf}function g(a){if(null==a._isValid){var d=p(a);a._isValid=!isNaN(a._d.getTime())&&0>d.overflow&&!d.empty&&!d.invalidMonth&&
    !d.invalidWeekday&&!d.nullInput&&!d.invalidFormat&&!d.userInvalidated;a._strict&&(a._isValid=a._isValid&&0===d.charsLeftOver&&0===d.unusedTokens.length&&void 0===d.bigHour)}return a._isValid}function y(a){var d=K(NaN);null!=a?r(p(d),a):p(d).userInvalidated=!0;return d}function wa(a,d){var b;"undefined"!==typeof d._isAMomentObject&&(a._isAMomentObject=d._isAMomentObject);"undefined"!==typeof d._i&&(a._i=d._i);"undefined"!==typeof d._f&&(a._f=d._f);"undefined"!==typeof d._l&&(a._l=d._l);"undefined"!==
typeof d._strict&&(a._strict=d._strict);"undefined"!==typeof d._tzm&&(a._tzm=d._tzm);"undefined"!==typeof d._isUTC&&(a._isUTC=d._isUTC);"undefined"!==typeof d._offset&&(a._offset=d._offset);"undefined"!==typeof d._pf&&(a._pf=p(d));"undefined"!==typeof d._locale&&(a._locale=d._locale);if(0<Za.length)for(b in Za){var c=Za[b];var e=d[c];"undefined"!==typeof e&&(a[c]=e)}return a}function J(a){wa(this,a);this._d=new Date(null!=a._d?a._d.getTime():NaN);!1===$a&&($a=!0,f.updateOffset(this),$a=!1)}function E(a){return a instanceof
    J||null!=a&&null!=a._isAMomentObject}function G(a){return 0>a?Math.ceil(a):Math.floor(a)}function v(a){a=+a;var d=0;0!==a&&isFinite(a)&&(d=G(a));return d}function La(a,d,b){var I=Math.min(a.length,d.length),c=Math.abs(a.length-d.length),e=0,f;for(f=0;f<I;f++)(b&&a[f]!==d[f]||!b&&v(a[f])!==v(d[f]))&&e++;return e+c}function F(){}function U(a){return a?a.toLowerCase().replace("_","-"):a}function la(a){var d=null;if(!qa[a]&&"undefined"!==typeof module&&module&&module.exports)try{d=Na._abbr,require("./locale/"+
    a),X(d)}catch(I){}return qa[a]}function X(a,d){var b;a&&(b="undefined"===typeof d?N(a):Ca(a,d))&&(Na=b);return Na._abbr}function Ca(a,d){if(null!==d)return d.abbr=a,qa[a]=qa[a]||new F,qa[a].set(d),X(a),qa[a];delete qa[a];return null}function N(a){var d;a&&a._locale&&a._locale._abbr&&(a=a._locale._abbr);if(!a)return Na;if(!n(a)){if(d=la(a))return d;a=[a]}a:{d=0;for(var b,c,e,f;d<a.length;){f=U(a[d]).split("-");b=f.length;for(c=(c=U(a[d+1]))?c.split("-"):null;0<b;){if(e=la(f.slice(0,b).join("-"))){a=
    e;break a}if(c&&c.length>=b&&La(f,c,!0)>=b-1)break;b--}d++}a=null}return a}function H(a,d){var b=a.toLowerCase();Fa[b]=Fa[b+"s"]=Fa[d]=a}function O(a){return"string"===typeof a?Fa[a]||Fa[a.toLowerCase()]:void 0}function aa(a){var d={},b,Ma;for(Ma in a)c(a,Ma)&&(b=O(Ma))&&(d[b]=a[Ma]);return d}function ba(a,d){return function(b){return null!=b?(this._d["set"+(this._isUTC?"UTC":"")+a](b),f.updateOffset(this,d),this):ka(this,a)}}function ka(a,d){return a._d["get"+(a._isUTC?"UTC":"")+d]()}function Da(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          d){var b;if("object"===typeof a)for(b in a)this.set(b,a[b]);else if(a=O(a),"function"===typeof this[a])return this[a](d);return this}function da(a,d,b){var c=""+Math.abs(a);return(0<=a?b?"+":"":"-")+Math.pow(10,Math.max(0,d-c.length)).toString().substr(1)+c}function m(a,d,b,c){var I=c;"string"===typeof c&&(I=function(){return this[c]()});a&&(Aa[a]=I);d&&(Aa[d[0]]=function(){return da(I.apply(this,arguments),d[1],d[2])});b&&(Aa[b]=function(){return this.localeData().ordinal(I.apply(this,arguments),
    a)})}function z(a){return a.match(/\[[\s\S]/)?a.replace(/^\[|\]$/g,""):a.replace(/\\/g,"")}function ma(a){var d=a.match(lb),b;var c=0;for(b=d.length;c<b;c++)d[c]=Aa[d[c]]?Aa[d[c]]:z(d[c]);return function(I){var e="";for(c=0;c<b;c++)e+=d[c]instanceof Function?d[c].call(I,a):d[c];return e}}function oa(a,d){if(!a.isValid())return a.localeData().invalidDate();d=ya(d,a.localeData());ab[d]=ab[d]||ma(d);return ab[d](a)}function ya(a,d){function b(a){return d.longDateFormat(a)||a}var c=5;for(Oa.lastIndex=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0;0<=c&&Oa.test(a);)a=a.replace(Oa,b),Oa.lastIndex=0,--c;return a}function k(a,d,b){bb[a]="function"===typeof d&&"[object Function]"===Object.prototype.toString.call(d)?d:function(a){return a&&b?b:d}}function Ia(a,d){return c(bb,a)?bb[a](d._strict,d._locale):new RegExp(Ya(a))}function Ya(a){return a.replace("\\","").replace(/\\(\[)|\\(\])|\[([^\]\[]*)\]|\\(.)/g,function(a,b,c,e,f){return b||c||e||f}).replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")}function D(a,d){var b,c=d;"string"===typeof a&&(a=[a]);"number"===
typeof d&&(c=function(a,b){b[d]=v(a)});for(b=0;b<a.length;b++)cb[a[b]]=c}function pa(a,d){D(a,function(a,b,c,e){c._w=c._w||{};d(a,c._w,c,e)})}function za(a,d){return(new Date(Date.UTC(a,d+1,0))).getUTCDate()}function Ka(a,d){if("string"===typeof d&&(d=a.localeData().monthsParse(d),"number"!==typeof d))return a;var b=Math.min(a.date(),za(a.year(),d));a._d["set"+(a._isUTC?"UTC":"")+"Month"](d,b);return a}function V(a){return null!=a?(Ka(this,a),f.updateOffset(this,!0),this):ka(this,"Month")}function W(a){var d;
    (d=a._a)&&-2===p(a).overflow&&(d=0>d[Y]||11<d[Y]?Y:1>d[S]||d[S]>za(d[T],d[Y])?S:0>d[P]||24<d[P]||24===d[P]&&(0!==d[ra]||0!==d[sa]||0!==d[ta])?P:0>d[ra]||59<d[ra]?ra:0>d[sa]||59<d[sa]?sa:0>d[ta]||999<d[ta]?ta:-1,p(a)._overflowDayOfYear&&(d<T||d>S)&&(d=S),p(a).overflow=d);return a}function xa(a){!1===f.suppressDeprecationWarnings&&"undefined"!==typeof console&&console.warn&&console.warn("Deprecation warning: "+a)}function L(a,d){var b=!0;return r(function(){b&&(xa(a+"\n"+Error().stack),b=!1);return d.apply(this,
    arguments)},d)}function Ja(a){var d,b=a._i,c=Kb.exec(b);if(c){p(a).iso=!0;var e=0;for(d=db.length;e<d;e++)if(db[e][1].exec(b)){a._f=db[e][0];break}e=0;for(d=eb.length;e<d;e++)if(eb[e][1].exec(b)){a._f+=(c[6]||" ")+eb[e][0];break}b.match(Pa)&&(a._f+="Z");Xa(a)}else a._isValid=!1}function b(a){var d=Lb.exec(a._i);null!==d?a._d=new Date(+d[1]):(Ja(a),!1===a._isValid&&(delete a._isValid,f.createFromInputFallback(a)))}function e(a,d,b,c,e,f,g){d=new Date(a,d,b,c,e,f,g);1970>a&&d.setFullYear(a);return d}
    function l(a){var d=new Date(Date.UTC.apply(null,arguments));1970>a&&d.setUTCFullYear(a);return d}function t(a){return 0===a%4&&0!==a%100||0===a%400}function ja(a,d,b){d=b-d;b-=a.day();b>d&&(b-=7);b<d-7&&(b+=7);a=w(a).add(b,"d");return{week:Math.ceil(a.dayOfYear()/7),year:a.year()}}function M(a,d,b){return null!=a?a:null!=d?d:b}function C(a){var d=[];if(!a._d){var b=new Date;b=a._useUTC?[b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate()]:[b.getFullYear(),b.getMonth(),b.getDate()];if(a._w&&null==a._a[S]&&
        null==a._a[Y]){var c=a._w;if(null!=c.GG||null!=c.W||null!=c.E){var f=1;var g=4;var h=M(c.GG,a._a[T],ja(w(),1,4).year);var k=M(c.W,1);c=M(c.E,1)}else f=a._locale._week.dow,g=a._locale._week.doy,h=M(c.gg,a._a[T],ja(w(),f,g).year),k=M(c.w,1),null!=c.d?(c=c.d,c<f&&++k):c=null!=c.e?c.e+f:f;g=6+f-g;var m=l(h,0,1+g).getUTCDay();m<f&&(m+=7);f=1+g+7*(k-1)-m+(null!=c?1*c:f);g=0<f?h:h-1;h=0<f?f:(t(h-1)?366:365)+f;a._a[T]=g;a._dayOfYear=h}a._dayOfYear&&(h=M(a._a[T],b[T]),a._dayOfYear>(t(h)?366:365)&&(p(a)._overflowDayOfYear=
        !0),h=l(h,0,a._dayOfYear),a._a[Y]=h.getUTCMonth(),a._a[S]=h.getUTCDate());for(h=0;3>h&&null==a._a[h];++h)a._a[h]=d[h]=b[h];for(;7>h;h++)a._a[h]=d[h]=null==a._a[h]?2===h?1:0:a._a[h];24===a._a[P]&&0===a._a[ra]&&0===a._a[sa]&&0===a._a[ta]&&(a._nextDay=!0,a._a[P]=0);a._d=(a._useUTC?l:e).apply(null,d);null!=a._tzm&&a._d.setUTCMinutes(a._d.getUTCMinutes()-a._tzm);a._nextDay&&(a._a[P]=24)}}function Xa(a){if(a._f===f.ISO_8601)Ja(a);else{a._a=[];p(a).empty=!0;var d=""+a._i,b,e,g=d.length,h=0;var k=ya(a._f,
        a._locale).match(lb)||[];for(b=0;b<k.length;b++){var l=k[b];if(e=(d.match(Ia(l,a))||[])[0]){var m=d.substr(0,d.indexOf(e));0<m.length&&p(a).unusedInput.push(m);d=d.slice(d.indexOf(e)+e.length);h+=e.length}if(Aa[l]){if(e?p(a).empty=!1:p(a).unusedTokens.push(l),m=a,null!=e&&c(cb,l))cb[l](e,m._a,m,l)}else a._strict&&!e&&p(a).unusedTokens.push(l)}p(a).charsLeftOver=g-h;0<d.length&&p(a).unusedInput.push(d);!0===p(a).bigHour&&12>=a._a[P]&&0<a._a[P]&&(p(a).bigHour=void 0);d=a._a;b=P;g=a._locale;k=a._a[P];
        h=a._meridiem;null!=h&&(null!=g.meridiemHour?k=g.meridiemHour(k,h):null!=g.isPM&&((g=g.isPM(h))&&12>k&&(k+=12),g||12!==k||(k=0)));d[b]=k;C(a);W(a)}}function na(a){if(!a._d){var d=aa(a._i);a._a=[d.year,d.month,d.day||d.date,d.hour,d.minute,d.second,d.millisecond];C(a)}}function ca(a){var d=a._i,b=a._f;a._locale=a._locale||N(a._l);if(null===d||void 0===b&&""===d)return y({nullInput:!0});"string"===typeof d&&(a._i=d=a._locale.preparse(d));if(E(d))return new J(W(d));if(n(b))if(0===a._f.length)p(a).invalidFormat=
        !0,a._d=new Date(NaN);else{for(d=0;d<a._f.length;d++){b=0;var c=wa({},a);null!=a._useUTC&&(c._useUTC=a._useUTC);c._f=a._f[d];Xa(c);if(g(c)&&(b+=p(c).charsLeftOver,b+=10*p(c).unusedTokens.length,p(c).score=b,null==e||b<e)){var e=b;var f=c}}r(a,f||c)}else b?Xa(a):x(d)?a._d=d:Ib(a);return a}function Ib(a){var d=a._i;void 0===d?a._d=new Date:x(d)?a._d=new Date(+d):"string"===typeof d?b(a):n(d)?(a._a=A(d.slice(0),function(a){return parseInt(a,10)}),C(a)):"object"===typeof d?na(a):"number"===typeof d?a._d=
        new Date(d):f.createFromInputFallback(a)}function Ea(a,d,b,c,e){var I={};"boolean"===typeof b&&(c=b,b=void 0);I._isAMomentObject=!0;I._useUTC=I._isUTC=e;I._l=b;I._i=a;I._f=d;I._strict=c;a=new J(W(ca(I)));a._nextDay&&(a.add(1,"d"),a._nextDay=void 0);return a}function w(a,d,b,c){return Ea(a,d,b,c,!1)}function mb(a,d){var b;1===d.length&&n(d[0])&&(d=d[0]);if(!d.length)return w();var c=d[0];for(b=1;b<d.length;++b)if(!d[b].isValid()||d[b][a](c))c=d[b];return c}function Qa(a){a=aa(a);var b=a.year||0,c=
        a.quarter||0,e=a.month||0,f=a.week||0,g=a.day||0;this._milliseconds=+(a.millisecond||0)+1E3*(a.second||0)+6E4*(a.minute||0)+36E5*(a.hour||0);this._days=+g+7*f;this._months=+e+3*c+12*b;this._data={};this._locale=N();this._bubble()}function fb(a){return a instanceof Qa}function nb(a,b){m(a,0,0,function(){var a=this.utcOffset(),d="+";0>a&&(a=-a,d="-");return d+da(~~(a/60),2)+b+da(~~a%60,2)})}function gb(a){a=(a||"").match(Pa)||[];a=((a[a.length-1]||[])+"").match(Mb)||["-",0,0];var b=+(60*a[1])+v(a[2]);
        return"+"===a[0]?b:-b}function hb(a,b){if(b._isUTC){var d=b.clone();var c=(E(a)||x(a)?+a:+w(a))-+d;d._d.setTime(+d._d+c);f.updateOffset(d,!1);return d}return w(a).local()}function ob(){return this._isUTC&&0===this._offset}function ea(a,b){var d=a,e;fb(a)?d={ms:a._milliseconds,d:a._days,M:a._months}:"number"===typeof a?(d={},b?d[b]=a:d.milliseconds=a):(e=Nb.exec(a))?(d="-"===e[1]?-1:1,d={y:0,d:v(e[S])*d,h:v(e[P])*d,m:v(e[ra])*d,s:v(e[sa])*d,ms:v(e[ta])*d}):(e=Ob.exec(a))?(d="-"===e[1]?-1:1,d={y:ua(e[2],
        d),M:ua(e[3],d),d:ua(e[4],d),h:ua(e[5],d),m:ua(e[6],d),s:ua(e[7],d),w:ua(e[8],d)}):null==d?d={}:"object"===typeof d&&("from"in d||"to"in d)&&(e=w(d.from),d=w(d.to),d=hb(d,e),e.isBefore(d)?d=pb(e,d):(d=pb(d,e),d.milliseconds=-d.milliseconds,d.months=-d.months),e=d,d={},d.ms=e.milliseconds,d.M=e.months);d=new Qa(d);fb(a)&&c(a,"_locale")&&(d._locale=a._locale);return d}function ua(a,d){var b=a&&parseFloat(a.replace(",","."));return(isNaN(b)?0:b)*d}function pb(a,d){var b={milliseconds:0,months:0};b.months=
        d.month()-a.month()+12*(d.year()-a.year());a.clone().add(b.months,"M").isAfter(d)&&--b.months;b.milliseconds=+d-+a.clone().add(b.months,"M");return b}function qb(a,d){return function(b,c){if(null!==c&&!isNaN(+c)){rb[d]||(xa("moment()."+d+"(period, number) is deprecated. Please use moment()."+d+"(number, period)."),rb[d]=!0);var e=b;b=c;c=e}e=ea("string"===typeof b?+b:b,c);sb(this,e,a);return this}}function sb(a,d,b,c){var e=d._milliseconds,g=d._days;d=d._months;c=null==c?!0:c;e&&a._d.setTime(+a._d+
        e*b);g&&(e=ka(a,"Date")+g*b,a._d["set"+(a._isUTC?"UTC":"")+"Date"](e));d&&Ka(a,ka(a,"Month")+d*b);c&&f.updateOffset(a,g||d)}function tb(){var a=this.clone().utc();return 0<a.year()&&9999>=a.year()?"function"===typeof Date.prototype.toISOString?this.toDate().toISOString():oa(a,"YYYY-MM-DD[T]HH:mm:ss.SSS[Z]"):oa(a,"YYYYYY-MM-DD[T]HH:mm:ss.SSS[Z]")}function ub(a){if(void 0===a)return this._locale._abbr;a=N(a);null!=a&&(this._locale=a);return this}function vb(){return this._locale}function Ra(a,d){m(0,
        [a,a.length],0,d)}function wb(a,d,b){return ja(w([a,11,31+d-b]),d,b).week}function xb(a,d){m(a,0,0,function(){return this.localeData().meridiem(this.hours(),this.minutes(),d)})}function yb(a,d){return d._meridiemParse}function Pb(a,d){d[ta]=v(1E3*("0."+a))}function zb(a){return a}function Ab(a,d,b,c){var e=N();d=K().set(c,d);return e[b](d,a)}function Ga(a,d,b,c,e){"number"===typeof a&&(d=a,a=void 0);a=a||"";if(null!=d)return Ab(a,d,b,e);var f=[];for(d=0;d<c;d++)f[d]=Ab(a,d,b,e);return f}function Bb(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                d,b,c){d=ea(d,b);a._milliseconds+=c*d._milliseconds;a._days+=c*d._days;a._months+=c*d._months;return a._bubble()}function Cb(a){return 0>a?Math.floor(a):Math.ceil(a)}function fa(a){return function(){return this.as(a)}}function va(a){return function(){return this._data[a]}}function Qb(a,b,c,e,f){return f.relativeTime(b||1,!!c,a,e)}function Sa(){var a=ib(this._milliseconds)/1E3,b=ib(this._days),c=ib(this._months);var e=G(a/60);var f=G(e/60);a%=60;e%=60;var g=G(c/12);c%=12;var h=this.asSeconds();return h?
        (0>h?"-":"")+"P"+(g?g+"Y":"")+(c?c+"M":"")+(b?b+"D":"")+(f||e||a?"T":"")+(f?f+"H":"")+(e?e+"M":"")+(a?a+"S":""):"P0D"}var Za=f.momentProperties=[],$a=!1,qa={},Na,Fa={},lb=/(\[[^\[]*\])|(\\)?(Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|Q|YYYYYY|YYYYY|YYYY|YY|gg(ggg?)?|GG(GGG?)?|e|E|a|A|hh?|HH?|mm?|ss?|S{1,9}|x|X|zz?|ZZ?|.)/g,Oa=/(\[[^\[]*\])|(\\)?(LTS|LT|LL?L?L?|l{1,4})/g,ab={},Aa={},Db=/\d/,R=/\d\d/,Eb=/\d{3}/,jb=/\d{4}/,Ta=/[+-]?\d{6}/,B=/\d\d?/,Ua=/\d{1,3}/,kb=/\d{1,4}/,Va=/[+-]?\d{1,6}/,
        Rb=/\d+/,Wa=/[+-]?\d+/,Pa=/Z|[+-]\d\d:?\d\d/gi,Ha=/[0-9]*['a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF\/]+(\s*?[\u0600-\u06FF]+){1,2}/i,bb={},cb={},T=0,Y=1,S=2,P=3,ra=4,sa=5,ta=6;m("M",["MM",2],"Mo",function(){return this.month()+1});m("MMM",0,0,function(a){return this.localeData().monthsShort(this,a)});m("MMMM",0,0,function(a){return this.localeData().months(this,a)});H("month","M");k("M",B);k("MM",B,R);k("MMM",Ha);k("MMMM",Ha);D(["M","MM"],function(a,b){b[Y]=v(a)-1});
    D(["MMM","MMMM"],function(a,b,c,e){e=c._locale.monthsParse(a,e,c._strict);null!=e?b[Y]=e:p(c).invalidMonth=a});var rb={};f.suppressDeprecationWarnings=!1;var Kb=/^\s*(?:[+-]\d{6}|\d{4})-(?:(\d\d-\d\d)|(W\d\d$)|(W\d\d-\d)|(\d\d\d))((T| )(\d\d(:\d\d(:\d\d(\.\d+)?)?)?)?([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/,db=[["YYYYYY-MM-DD",/[+-]\d{6}-\d{2}-\d{2}/],["YYYY-MM-DD",/\d{4}-\d{2}-\d{2}/],["GGGG-[W]WW-E",/\d{4}-W\d{2}-\d/],["GGGG-[W]WW",/\d{4}-W\d{2}/],["YYYY-DDD",/\d{4}-\d{3}/]],eb=[["HH:mm:ss.SSSS",/(T| )\d\d:\d\d:\d\d\.\d+/],
        ["HH:mm:ss",/(T| )\d\d:\d\d:\d\d/],["HH:mm",/(T| )\d\d:\d\d/],["HH",/(T| )\d\d/]],Lb=/^\/?Date\((\-?\d+)/i;f.createFromInputFallback=L("moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.",function(a){a._d=new Date(a._i+(a._useUTC?" UTC":""))});m(0,["YY",2],0,function(){return this.year()%100});m(0,["YYYY",4],0,"year");m(0,["YYYYY",5],0,"year");m(0,["YYYYYY",6,!0],
        0,"year");H("year","y");k("Y",Wa);k("YY",B,R);k("YYYY",kb,jb);k("YYYYY",Va,Ta);k("YYYYYY",Va,Ta);D(["YYYYY","YYYYYY"],T);D("YYYY",function(a,b){b[T]=2===a.length?f.parseTwoDigitYear(a):v(a)});D("YY",function(a,b){b[T]=f.parseTwoDigitYear(a)});f.parseTwoDigitYear=function(a){return v(a)+(68<v(a)?1900:2E3)};var Fb=ba("FullYear",!1);m("w",["ww",2],"wo","week");m("W",["WW",2],"Wo","isoWeek");H("week","w");H("isoWeek","W");k("w",B);k("ww",B,R);k("W",B);k("WW",B,R);pa(["w","ww","W","WW"],function(a,b,c,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        e){b[e.substr(0,1)]=v(a)});m("DDD",["DDDD",3],"DDDo","dayOfYear");H("dayOfYear","DDD");k("DDD",Ua);k("DDDD",Eb);D(["DDD","DDDD"],function(a,b,c){c._dayOfYear=v(a)});f.ISO_8601=function(){};var Sb=L("moment().min is deprecated, use moment.min instead. https://github.com/moment/moment/issues/1548",function(){var a=w.apply(null,arguments);return a<this?this:a}),Tb=L("moment().max is deprecated, use moment.max instead. https://github.com/moment/moment/issues/1548",function(){var a=w.apply(null,arguments);
        return a>this?this:a});nb("Z",":");nb("ZZ","");k("Z",Pa);k("ZZ",Pa);D(["Z","ZZ"],function(a,b,c){c._useUTC=!0;c._tzm=gb(a)});var Mb=/([\+\-]|\d\d)/gi;f.updateOffset=function(){};var Nb=/(\-)?(?:(\d*)\.)?(\d+)\:(\d+)(?:\:(\d+)\.?(\d{3})?)?/,Ob=/^(-)?P(?:(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?|([0-9,.]*)W)$/;ea.fn=Qa.prototype;var Ub=qb(1,"add"),Vb=qb(-1,"subtract");f.defaultFormat="YYYY-MM-DDTHH:mm:ssZ";var Gb=L("moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.",
        function(a){return void 0===a?this.localeData():this.locale(a)});m(0,["gg",2],0,function(){return this.weekYear()%100});m(0,["GG",2],0,function(){return this.isoWeekYear()%100});Ra("gggg","weekYear");Ra("ggggg","weekYear");Ra("GGGG","isoWeekYear");Ra("GGGGG","isoWeekYear");H("weekYear","gg");H("isoWeekYear","GG");k("G",Wa);k("g",Wa);k("GG",B,R);k("gg",B,R);k("GGGG",kb,jb);k("gggg",kb,jb);k("GGGGG",Va,Ta);k("ggggg",Va,Ta);pa(["gggg","ggggg","GGGG","GGGGG"],function(a,b,c,e){b[e.substr(0,2)]=v(a)});
    pa(["gg","GG"],function(a,b,c,e){b[e]=f.parseTwoDigitYear(a)});m("Q",0,0,"quarter");H("quarter","Q");k("Q",Db);D("Q",function(a,b){b[Y]=3*(v(a)-1)});m("D",["DD",2],"Do","date");H("date","D");k("D",B);k("DD",B,R);k("Do",function(a,b){return a?b._ordinalParse:b._ordinalParseLenient});D(["D","DD"],S);D("Do",function(a,b){b[S]=v(a.match(B)[0],10)});var Hb=ba("Date",!0);m("d",0,"do","day");m("dd",0,0,function(a){return this.localeData().weekdaysMin(this,a)});m("ddd",0,0,function(a){return this.localeData().weekdaysShort(this,
        a)});m("dddd",0,0,function(a){return this.localeData().weekdays(this,a)});m("e",0,0,"weekday");m("E",0,0,"isoWeekday");H("day","d");H("weekday","e");H("isoWeekday","E");k("d",B);k("e",B);k("E",B);k("dd",Ha);k("ddd",Ha);k("dddd",Ha);pa(["dd","ddd","dddd"],function(a,b,c){var d=c._locale.weekdaysParse(a);null!=d?b.d=d:p(c).invalidWeekday=a});pa(["d","e","E"],function(a,b,c,e){b[e]=v(a)});m("H",["HH",2],0,"hour");m("h",["hh",2],0,function(){return this.hours()%12||12});xb("a",!0);xb("A",!1);H("hour",
        "h");k("a",yb);k("A",yb);k("H",B);k("h",B);k("HH",B,R);k("hh",B,R);D(["H","HH"],P);D(["a","A"],function(a,b,c){c._isPm=c._locale.isPM(a);c._meridiem=a});D(["h","hh"],function(a,b,c){b[P]=v(a);p(c).bigHour=!0});var Wb=ba("Hours",!0);m("m",["mm",2],0,"minute");H("minute","m");k("m",B);k("mm",B,R);D(["m","mm"],ra);var Xb=ba("Minutes",!1);m("s",["ss",2],0,"second");H("second","s");k("s",B);k("ss",B,R);D(["s","ss"],sa);var Yb=ba("Seconds",!1);m("S",0,0,function(){return~~(this.millisecond()/100)});m(0,
        ["SS",2],0,function(){return~~(this.millisecond()/10)});m(0,["SSS",3],0,"millisecond");m(0,["SSSS",4],0,function(){return 10*this.millisecond()});m(0,["SSSSS",5],0,function(){return 100*this.millisecond()});m(0,["SSSSSS",6],0,function(){return 1E3*this.millisecond()});m(0,["SSSSSSS",7],0,function(){return 1E4*this.millisecond()});m(0,["SSSSSSSS",8],0,function(){return 1E5*this.millisecond()});m(0,["SSSSSSSSS",9],0,function(){return 1E6*this.millisecond()});H("millisecond","ms");k("S",Ua,Db);k("SS",
        Ua,R);k("SSS",Ua,Eb);var ha;for(ha="SSSS";9>=ha.length;ha+="S")k(ha,Rb);for(ha="S";9>=ha.length;ha+="S")D(ha,Pb);var Zb=ba("Milliseconds",!1);m("z",0,0,"zoneAbbr");m("zz",0,0,"zoneName");var h=J.prototype;h.add=Ub;h.calendar=function(a,b){var d=a||w(),c=hb(d,this).startOf("day");c=this.diff(c,"days",!0);c=-6>c?"sameElse":-1>c?"lastWeek":0>c?"lastDay":1>c?"sameDay":2>c?"nextDay":7>c?"nextWeek":"sameElse";return this.format(b&&b[c]||this.localeData().calendar(c,this,w(d)))};h.clone=function(){return new J(this)};
    h.diff=function(a,b,c){a=hb(a,this);var d=6E4*(a.utcOffset()-this.utcOffset());b=O(b);if("year"===b||"month"===b||"quarter"===b){d=12*(a.year()-this.year())+(a.month()-this.month());var e=this.clone().add(d,"months");if(0>a-e){var f=this.clone().add(d-1,"months");a=(a-e)/(e-f)}else f=this.clone().add(d+1,"months"),a=(a-e)/(f-e);a=-(d+a);"quarter"===b?a/=3:"year"===b&&(a/=12)}else a=this-a,a="second"===b?a/1E3:"minute"===b?a/6E4:"hour"===b?a/36E5:"day"===b?(a-d)/864E5:"week"===b?(a-d)/6048E5:a;return c?
        a:G(a)};h.endOf=function(a){a=O(a);return void 0===a||"millisecond"===a?this:this.startOf(a).add(1,"isoWeek"===a?"week":a).subtract(1,"ms")};h.format=function(a){a=oa(this,a||f.defaultFormat);return this.localeData().postformat(a)};h.from=function(a,b){return this.isValid()?ea({to:this,from:a}).locale(this.locale()).humanize(!b):this.localeData().invalidDate()};h.fromNow=function(a){return this.from(w(),a)};h.to=function(a,b){return this.isValid()?ea({from:this,to:a}).locale(this.locale()).humanize(!b):
        this.localeData().invalidDate()};h.toNow=function(a){return this.to(w(),a)};h.get=Da;h.invalidAt=function(){return p(this).overflow};h.isAfter=function(a,b){b=O("undefined"!==typeof b?b:"millisecond");return"millisecond"===b?(a=E(a)?a:w(a),+this>+a):(E(a)?+a:+w(a))<+this.clone().startOf(b)};h.isBefore=function(a,b){b=O("undefined"!==typeof b?b:"millisecond");if("millisecond"===b)return a=E(a)?a:w(a),+this<+a;var d=E(a)?+a:+w(a);return+this.clone().endOf(b)<d};h.isBetween=function(a,b,c){return this.isAfter(a,
        c)&&this.isBefore(b,c)};h.isSame=function(a,b){b=O(b||"millisecond");if("millisecond"===b)return a=E(a)?a:w(a),+this===+a;var d=+w(a);return+this.clone().startOf(b)<=d&&d<=+this.clone().endOf(b)};h.isValid=function(){return g(this)};h.lang=Gb;h.locale=ub;h.localeData=vb;h.max=Tb;h.min=Sb;h.parsingFlags=function(){return r({},p(this))};h.set=Da;h.startOf=function(a){a=O(a);switch(a){case "year":this.month(0);case "quarter":case "month":this.date(1);case "week":case "isoWeek":case "day":this.hours(0);
        case "hour":this.minutes(0);case "minute":this.seconds(0);case "second":this.milliseconds(0)}"week"===a&&this.weekday(0);"isoWeek"===a&&this.isoWeekday(1);"quarter"===a&&this.month(3*Math.floor(this.month()/3));return this};h.subtract=Vb;h.toArray=function(){return[this.year(),this.month(),this.date(),this.hour(),this.minute(),this.second(),this.millisecond()]};h.toObject=function(){return{years:this.year(),months:this.month(),date:this.date(),hours:this.hours(),minutes:this.minutes(),seconds:this.seconds(),
        milliseconds:this.milliseconds()}};h.toDate=function(){return this._offset?new Date(+this):this._d};h.toISOString=tb;h.toJSON=tb;h.toString=function(){return this.clone().locale("en").format("ddd MMM DD YYYY HH:mm:ss [GMT]ZZ")};h.unix=function(){return Math.floor(+this/1E3)};h.valueOf=function(){return+this._d-6E4*(this._offset||0)};h.year=Fb;h.isLeapYear=function(){return t(this.year())};h.weekYear=function(a){var b=ja(this,this.localeData()._week.dow,this.localeData()._week.doy).year;return null==
    a?b:this.add(a-b,"y")};h.isoWeekYear=function(a){var b=ja(this,1,4).year;return null==a?b:this.add(a-b,"y")};h.quarter=h.quarters=function(a){return null==a?Math.ceil((this.month()+1)/3):this.month(3*(a-1)+this.month()%3)};h.month=V;h.daysInMonth=function(){return za(this.year(),this.month())};h.week=h.weeks=function(a){var b=this.localeData().week(this);return null==a?b:this.add(7*(a-b),"d")};h.isoWeek=h.isoWeeks=function(a){var b=ja(this,1,4).week;return null==a?b:this.add(7*(a-b),"d")};h.weeksInYear=
        function(){var a=this.localeData()._week;return wb(this.year(),a.dow,a.doy)};h.isoWeeksInYear=function(){return wb(this.year(),1,4)};h.date=Hb;h.day=h.days=function(a){var b=this._isUTC?this._d.getUTCDay():this._d.getDay();if(null!=a){var c=this.localeData();"string"===typeof a&&(isNaN(a)?(a=c.weekdaysParse(a),a="number"===typeof a?a:null):a=parseInt(a,10));return this.add(a-b,"d")}return b};h.weekday=function(a){var b=(this.day()+7-this.localeData()._week.dow)%7;return null==a?b:this.add(a-b,"d")};
    h.isoWeekday=function(a){return null==a?this.day()||7:this.day(this.day()%7?a:a-7)};h.dayOfYear=function(a){var b=Math.round((this.clone().startOf("day")-this.clone().startOf("year"))/864E5)+1;return null==a?b:this.add(a-b,"d")};h.hour=h.hours=Wb;h.minute=h.minutes=Xb;h.second=h.seconds=Yb;h.millisecond=h.milliseconds=Zb;h.utcOffset=function(a,b){var d=this._offset||0,c;return null!=a?("string"===typeof a&&(a=gb(a)),16>Math.abs(a)&&(a*=60),!this._isUTC&&b&&(c=15*-Math.round(this._d.getTimezoneOffset()/
        15)),this._offset=a,this._isUTC=!0,null!=c&&this.add(c,"m"),d!==a&&(!b||this._changeInProgress?sb(this,ea(a-d,"m"),1,!1):this._changeInProgress||(this._changeInProgress=!0,f.updateOffset(this,!0),this._changeInProgress=null)),this):this._isUTC?d:15*-Math.round(this._d.getTimezoneOffset()/15)};h.utc=function(a){return this.utcOffset(0,a)};h.local=function(a){this._isUTC&&(this.utcOffset(0,a),this._isUTC=!1,a&&this.subtract(15*-Math.round(this._d.getTimezoneOffset()/15),"m"));return this};h.parseZone=
        function(){this._tzm?this.utcOffset(this._tzm):"string"===typeof this._i&&this.utcOffset(gb(this._i));return this};h.hasAlignedHourOffset=function(a){a=a?w(a).utcOffset():0;return 0===(this.utcOffset()-a)%60};h.isDST=function(){return this.utcOffset()>this.clone().month(0).utcOffset()||this.utcOffset()>this.clone().month(5).utcOffset()};h.isDSTShifted=function(){if("undefined"!==typeof this._isDSTShifted)return this._isDSTShifted;var a={};wa(a,this);a=ca(a);if(a._a){var b=a._isUTC?K(a._a):w(a._a);
        this._isDSTShifted=this.isValid()&&0<La(a._a,b.toArray())}else this._isDSTShifted=!1;return this._isDSTShifted};h.isLocal=function(){return!this._isUTC};h.isUtcOffset=function(){return this._isUTC};h.isUtc=ob;h.isUTC=ob;h.zoneAbbr=function(){return this._isUTC?"UTC":""};h.zoneName=function(){return this._isUTC?"Coordinated Universal Time":""};h.dates=L("dates accessor is deprecated. Use date instead.",Hb);h.months=L("months accessor is deprecated. Use month instead",V);h.years=L("years accessor is deprecated. Use year instead",
        Fb);h.zone=L("moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779",function(a,b){return null!=a?("string"!==typeof a&&(a=-a),this.utcOffset(a,b),this):-this.utcOffset()});var q=F.prototype;q._calendar={sameDay:"[Today at] LT",nextDay:"[Tomorrow at] LT",nextWeek:"dddd [at] LT",lastDay:"[Yesterday at] LT",lastWeek:"[Last] dddd [at] LT",sameElse:"L"};q.calendar=function(a,b,c){a=this._calendar[a];return"function"===typeof a?a.call(b,c):a};q._longDateFormat=
        {LTS:"h:mm:ss A",LT:"h:mm A",L:"MM/DD/YYYY",LL:"MMMM D, YYYY",LLL:"MMMM D, YYYY h:mm A",LLLL:"dddd, MMMM D, YYYY h:mm A"};q.longDateFormat=function(a){var b=this._longDateFormat[a],c=this._longDateFormat[a.toUpperCase()];if(b||!c)return b;this._longDateFormat[a]=c.replace(/MMMM|MM|DD|dddd/g,function(a){return a.slice(1)});return this._longDateFormat[a]};q._invalidDate="Invalid date";q.invalidDate=function(){return this._invalidDate};q._ordinal="%d";q.ordinal=function(a){return this._ordinal.replace("%d",
        a)};q._ordinalParse=/\d{1,2}/;q.preparse=zb;q.postformat=zb;q._relativeTime={future:"in %s",past:"%s ago",s:"a few seconds",m:"a minute",mm:"%d minutes",h:"an hour",hh:"%d hours",d:"a day",dd:"%d days",M:"a month",MM:"%d months",y:"a year",yy:"%d years"};q.relativeTime=function(a,b,c,e){var d=this._relativeTime[c];return"function"===typeof d?d(a,b,c,e):d.replace(/%d/i,a)};q.pastFuture=function(a,b){var c=this._relativeTime[0<a?"future":"past"];return"function"===typeof c?c(b):c.replace(/%s/i,b)};
    q.set=function(a){var b;for(b in a){var c=a[b];"function"===typeof c?this[b]=c:this["_"+b]=c}this._ordinalParseLenient=new RegExp(this._ordinalParse.source+"|"+/\d{1,2}/.source)};q.months=function(a){return this._months[a.month()]};q._months="January February March April May June July August September October November December".split(" ");q.monthsShort=function(a){return this._monthsShort[a.month()]};q._monthsShort="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");q.monthsParse=function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           b,c){var d;this._monthsParse||(this._monthsParse=[],this._longMonthsParse=[],this._shortMonthsParse=[]);for(d=0;12>d;d++){var e=K([2E3,d]);c&&!this._longMonthsParse[d]&&(this._longMonthsParse[d]=new RegExp("^"+this.months(e,"").replace(".","")+"$","i"),this._shortMonthsParse[d]=new RegExp("^"+this.monthsShort(e,"").replace(".","")+"$","i"));c||this._monthsParse[d]||(e="^"+this.months(e,"")+"|^"+this.monthsShort(e,""),this._monthsParse[d]=new RegExp(e.replace(".",""),"i"));if(c&&"MMMM"===b&&this._longMonthsParse[d].test(a)||
        c&&"MMM"===b&&this._shortMonthsParse[d].test(a)||!c&&this._monthsParse[d].test(a))return d}};q.week=function(a){return ja(a,this._week.dow,this._week.doy).week};q._week={dow:0,doy:6};q.firstDayOfYear=function(){return this._week.doy};q.firstDayOfWeek=function(){return this._week.dow};q.weekdays=function(a){return this._weekdays[a.day()]};q._weekdays="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");q.weekdaysMin=function(a){return this._weekdaysMin[a.day()]};q._weekdaysMin="Su Mo Tu We Th Fr Sa".split(" ");
    q.weekdaysShort=function(a){return this._weekdaysShort[a.day()]};q._weekdaysShort="Sun Mon Tue Wed Thu Fri Sat".split(" ");q.weekdaysParse=function(a){var b;this._weekdaysParse=this._weekdaysParse||[];for(b=0;7>b;b++){if(!this._weekdaysParse[b]){var c=w([2E3,1]).day(b);c="^"+this.weekdays(c,"")+"|^"+this.weekdaysShort(c,"")+"|^"+this.weekdaysMin(c,"");this._weekdaysParse[b]=new RegExp(c.replace(".",""),"i")}if(this._weekdaysParse[b].test(a))return b}};q.isPM=function(a){return"p"===(a+"").toLowerCase().charAt(0)};
    q._meridiemParse=/[ap]\.?m?\.?/i;q.meridiem=function(a,b,c){return 11<a?c?"pm":"PM":c?"am":"AM"};X("en",{ordinalParse:/\d{1,2}(th|st|nd|rd)/,ordinal:function(a){var b=a%10;b=1===v(a%100/10)?"th":1===b?"st":2===b?"nd":3===b?"rd":"th";return a+b}});f.lang=L("moment.lang is deprecated. Use moment.locale instead.",X);f.langData=L("moment.langData is deprecated. Use moment.localeData instead.",N);var Z=Math.abs,$b=fa("ms"),ac=fa("s"),bc=fa("m"),cc=fa("h"),dc=fa("d"),ec=fa("w"),fc=fa("M"),gc=fa("y"),hc=
        va("milliseconds"),ic=va("seconds"),jc=va("minutes"),kc=va("hours"),lc=va("days"),mc=va("months"),nc=va("years"),Ba=Math.round,ia={s:45,m:45,h:22,d:26,M:11},ib=Math.abs,u=Qa.prototype;u.abs=function(){var a=this._data;this._milliseconds=Z(this._milliseconds);this._days=Z(this._days);this._months=Z(this._months);a.milliseconds=Z(a.milliseconds);a.seconds=Z(a.seconds);a.minutes=Z(a.minutes);a.hours=Z(a.hours);a.months=Z(a.months);a.years=Z(a.years);return this};u.add=function(a,b){return Bb(this,a,
        b,1)};u.subtract=function(a,b){return Bb(this,a,b,-1)};u.as=function(a){var b=this._milliseconds;a=O(a);if("month"===a||"year"===a){var c=this._days+b/864E5;c=this._months+4800*c/146097;return"month"===a?c:c/12}c=this._days+Math.round(146097*this._months/4800);switch(a){case "week":return c/7+b/6048E5;case "day":return c+b/864E5;case "hour":return 24*c+b/36E5;case "minute":return 1440*c+b/6E4;case "second":return 86400*c+b/1E3;case "millisecond":return Math.floor(864E5*c)+b;default:throw Error("Unknown unit "+
        a);}};u.asMilliseconds=$b;u.asSeconds=ac;u.asMinutes=bc;u.asHours=cc;u.asDays=dc;u.asWeeks=ec;u.asMonths=fc;u.asYears=gc;u.valueOf=function(){return this._milliseconds+864E5*this._days+this._months%12*2592E6+31536E6*v(this._months/12)};u._bubble=function(){var a=this._milliseconds,b=this._days,c=this._months,e=this._data;0<=a&&0<=b&&0<=c||0>=a&&0>=b&&0>=c||(a+=864E5*Cb(146097*c/4800+b),c=b=0);e.milliseconds=a%1E3;a=G(a/1E3);e.seconds=a%60;a=G(a/60);e.minutes=a%60;a=G(a/60);e.hours=a%24;b+=G(a/24);
        a=G(4800*b/146097);c+=a;b-=Cb(146097*a/4800);a=G(c/12);e.days=b;e.months=c%12;e.years=a;return this};u.get=function(a){a=O(a);return this[a+"s"]()};u.milliseconds=hc;u.seconds=ic;u.minutes=jc;u.hours=kc;u.days=lc;u.weeks=function(){return G(this.days()/7)};u.months=mc;u.years=nc;u.humanize=function(a){var b=this.localeData();var c=!a;var e=ea(this).abs(),f=Ba(e.as("s")),g=Ba(e.as("m")),h=Ba(e.as("h")),k=Ba(e.as("d")),l=Ba(e.as("M"));e=Ba(e.as("y"));f=f<ia.s&&["s",f]||1===g&&["m"]||g<ia.m&&["mm",g]||
        1===h&&["h"]||h<ia.h&&["hh",h]||1===k&&["d"]||k<ia.d&&["dd",k]||1===l&&["M"]||l<ia.M&&["MM",l]||1===e&&["y"]||["yy",e];f[2]=c;f[3]=0<+this;f[4]=b;c=Qb.apply(null,f);a&&(c=b.pastFuture(+this,c));return b.postformat(c)};u.toISOString=Sa;u.toString=Sa;u.toJSON=Sa;u.locale=ub;u.localeData=vb;u.toIsoString=L("toIsoString() is deprecated. Please use toISOString() instead (notice the capitals)",Sa);u.lang=Gb;m("X",0,0,"unix");m("x",0,0,"valueOf");k("x",Wa);k("X",/[+-]?\d+(\.\d{1,3})?/);D("X",function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           b,c){c._d=new Date(1E3*parseFloat(a,10))});D("x",function(a,b,c){c._d=new Date(v(a))});f.version="2.10.6";var Jb=w;f.fn=h;f.min=function(){var a=[].slice.call(arguments,0);return mb("isBefore",a)};f.max=function(){var a=[].slice.call(arguments,0);return mb("isAfter",a)};f.utc=K;f.unix=function(a){return w(1E3*a)};f.months=function(a,b){return Ga(a,b,"months",12,"month")};f.isDate=x;f.locale=X;f.invalid=y;f.duration=ea;f.isMoment=E;f.weekdays=function(a,b){return Ga(a,b,"weekdays",7,"day")};f.parseZone=
        function(){return w.apply(null,arguments).parseZone()};f.localeData=N;f.isDuration=fb;f.monthsShort=function(a,b){return Ga(a,b,"monthsShort",12,"month")};f.weekdaysMin=function(a,b){return Ga(a,b,"weekdaysMin",7,"day")};f.defineLocale=Ca;f.weekdaysShort=function(a,b){return Ga(a,b,"weekdaysShort",7,"day")};f.normalizeUnits=O;f.relativeTimeThreshold=function(a,b){if(void 0===ia[a])return!1;if(void 0===b)return ia[a];ia[a]=b;return!0};return f});
getUrls=function(f,n){this.getManifest(f).then(this.getSegmentsAndByteLengthFromManifest.bind(this)).then(function(f){var x=[],c;for(c in f.segments)for(var r in f.segments[c].fragments)x.push(f.segments[c].fragments[r].url);n(x)})["catch"](function(f){console.error(f)})};
getSegmentsAndByteLengthFromManifest=function(f){var n=this,x=[],A=$(f.find("MPD")[0]).attr("mediaPresentationDuration"),c=moment.duration(A).asMilliseconds(),r=0;console.info("MEDIA DURATION",c);f.find("AdaptationSet").each(function(f,p){try{var g=$(p),y=$(g.find("SegmentTemplate")[0]),A=y.attr("media"),J=y.attr("initialization"),E=Number(y.attr("duration"))/Number(y.attr("timescale"))*1E3,G=Math.ceil(c/E),v=Number(y.attr("startNumber"));y={};E={startNumber:v,fragments:[]};var K=0,F,U=[];g.find("Representation").each(function(c,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     f){var g=$(f),n=Number(g.attr("bandwidth"));g=g.attr("id");U.push(g);n>K&&(K=n,F=g)});r+=K;var la="("+U.map(n.escapeRegExp).join("|")+")";y.urlTemplate=J.replace("$RepresentationID$",F);y.matchingFileName=n.getFileName(J).replace("$RepresentationID$",F);y.matchingUrl=n.escapeRegExp(J).replace(n.escapeRegExp("$RepresentationID$"),la);y.fragments=[{url:y.urlTemplate}];E.urlTemplate=A.replace("$RepresentationID$",F);E.matchingFileName=n.getFileName(A).replace("$RepresentationID$",F);E.matchingUrl=n.escapeRegExp(A).replace(n.escapeRegExp("$Number$"),
    "(\\d+)").replace(n.escapeRegExp("$RepresentationID$"),la);g=v;for(G+=v;g<G;++g)E.fragments.push({url:E.urlTemplate.replace("$Number$",g)});x.push(y,E)}catch(X){}});r=Math.ceil(r*c/8/1E3*1.25+102400);console.info("SEGMENTS",x);return{segments:x,byteLength:r}};getManifest=function(f){return this.xhrGet(f).then(function(f){return $($.parseXML(f))})["catch"](function(f){console.error("FAILED LOADING MANIFEST")})};getLls=function(f){return Q(!f&&this.lls||this.requestLls(f))};
requestLls=function(f){var n=this,x=this.getConfig("requestedStorageSize");return!f&&this.llsPromise||(this.llsPromise=(new LargeLocalStorage({size:x,name:this.getConfig("contentId")})).initialized.then(function(f){var c=f.getCapacity();console.info("INITIALIZED LLS WITH CAPACITY:",c,x);return c<x?Q.reject(f):f})["catch"](function(){n.llsPromise=null;n.sendNotification("userFsDenial");console.error("ERROR CREATING LLS. USER DENIAL.")}))};getFileName=function(f){return f.split("/").pop()};
readAttachment=function(f,n,x){var A=this;return this.getLls().then(function(c){return c.getAttachment(f,n).then(function(c){console.info("ATTACHMENT READ SUCCESSFULLY:",f+"/"+n,c);return c?A.readFile(c,x):Q.reject(c)})})};
xhrGet=function(f,n){var x=Q.defer(),A=new XMLHttpRequest;A.responseType=n||"text";A.open("GET",f,!0);A.onreadystatechange=function(){4===A.readyState&&(200<=A.status&&400>A.status?x.resolve(A.response):x.reject({status:A.status}))};A.onprogress=function(c){x.notify(c)};A.send("");return x.promise};escapeRegExp=function(f){return f.trim().replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")};