/*
 Copyright 2009-2017 Kris Kowal under the terms of the MIT
 license found at https://github.com/kriskowal/q/blob/v1/LICENSE

 With parts by Tyler Close
 Copyright 2007-2009 Tyler Close under the terms of the MIT X license found
 at http://www.opensource.org/licenses/mit-license.html
 Forked at ref_send.js version: 2009-05-11

 With parts by Mark Miller
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

*/
(function(f){if("function"===typeof bootstrap)bootstrap("promise",f);else if("object"===typeof exports&&"object"===typeof module)module.exports=f();else if("function"===typeof define&&define.amd)define(f);else if("undefined"!==typeof ses)ses.ok()&&(ses.makeQ=f);else if("undefined"!==typeof window||"undefined"!==typeof self){var p="undefined"!==typeof window?window:self,y=p.Q;p.Q=f();p.Q.noConflict=function(){p.Q=y;return this}}else throw Error("This environment was not anticipated by Q. Please file a bug.");
})(function(){function f(b){return function(){return m.apply(b,arguments)}}function p(b,e){if(ba&&e.stack&&"object"===typeof b&&null!==b&&b.stack){for(var c=[],r=e;r;r=r.source)r.stack&&(!b.__minimumStackCounter__||b.__minimumStackCounter__>r.stackCounter)&&(Ja(b,"__minimumStackCounter__",{value:r.stackCounter,configurable:!0}),c.unshift(r.stack));c.unshift(b.stack);c=c.join("\nFrom previous event:\n").split("\n");r=[];for(var f=0;f<c.length;++f){var g=c[f],B;if(B=y(g)){var k=B[1];B=B[0]===na&&k>=
    ca&&k<=Ka}else B=!1;B||(B=g,B=-1!==B.indexOf("(module.js:")||-1!==B.indexOf("(node.js:"));B||!g||r.push(g)}c=r.join("\n");Ja(b,"stack",{value:c,configurable:!0})}}function y(b){var e=/at .+ \((.+):(\d+):(?:\d+)\)$/.exec(b);if(e||(e=/at ([^ ]+):(\d+):(?:\d+)$/.exec(b)))return[e[1],Number(e[2])];if(b=/.*@(.+):(\d+)$/.exec(b))return[b[1],Number(b[2])]}function C(){if(ba)try{throw Error();}catch(e){var b=e.stack.split("\n");b=0<b[0].indexOf("@")?b[1]:b[2];if(b=y(b))return na=b[0],b[1]}}function c(b){return b instanceof
g?b:L(b)?da(b):N(b)}function u(){function b(b){r=b;c.longStackSupport&&ba&&(K.source=b);oa(e,function(e,l){c.nextTick(function(){b.promiseDispatch.apply(b,l)})},void 0);l=e=void 0}var e=[],l=[],r,f=k(u.prototype),K=k(g.prototype);K.promiseDispatch=function(b,f,g){var B=z(arguments);e?(e.push(B),"when"===f&&g[1]&&l.push(g[1])):c.nextTick(function(){r.promiseDispatch.apply(r,B)})};K.valueOf=function(){if(e)return K;var b=ya(r);I(b)&&(r=b);return b};K.inspect=function(){return r?r.inspect():{state:"pending"}};
    if(c.longStackSupport&&ba)try{throw Error();}catch(B){K.stack=B.stack.substring(B.stack.indexOf("\n")+1),K.stackCounter=La++}f.promise=K;f.resolve=function(e){r||b(c(e))};f.fulfill=function(e){r||b(N(e))};f.reject=function(e){r||b(D(e))};f.notify=function(b){r||oa(l,function(e,l){c.nextTick(function(){l(b)})},void 0)};return f}function G(b){if("function"!==typeof b)throw new TypeError("resolver must be a function.");var e=u();try{b(e.resolve,e.reject,e.notify)}catch(l){e.reject(l)}return e.promise}
    function n(b){return G(function(e,l){for(var f=0,g=b.length;f<g;f++)c(b[f]).then(e,l)})}function g(b,e,c){void 0===e&&(e=function(b){return D(Error("Promise does not support operation: "+b))});void 0===c&&(c=function(){return{state:"unknown"}});var l=k(g.prototype);l.promiseDispatch=function(c,f,r){try{var g=b[f]?b[f].apply(l,r):e.call(l,f,r)}catch(ea){g=D(ea)}c&&c(g)};if(l.inspect=c){var f=c();"rejected"===f.state&&(l.exception=f.reason);l.valueOf=function(){var b=c();return"pending"===b.state||
    "rejected"===b.state?l:b.value}}return l}function R(b,e,l,f){return c(b).then(e,l,f)}function ya(b){if(I(b)){var e=b.inspect();if("fulfilled"===e.state)return e.value}return b}function I(b){return b instanceof g}function L(b){return b===Object(b)&&"function"===typeof b.then}function H(){W.length=0;X.length=0;J||(J=!0)}function w(b,e){J&&("object"===typeof process&&"function"===typeof process.emit&&c.nextTick.runAfter(function(){-1!==qa(X,b)&&(process.emit("unhandledRejection",e,b),za.push(b))}),X.push(b),
        e&&"undefined"!==typeof e.stack?W.push(e.stack):W.push("(no stack) "+e))}function fa(b){if(J){var e=qa(X,b);-1!==e&&("object"===typeof process&&"function"===typeof process.emit&&c.nextTick.runAfter(function(){var c=qa(za,b);-1!==c&&(process.emit("rejectionHandled",W[e],b),za.splice(c,1))}),X.splice(e,1),W.splice(e,1))}}function D(b){var e=g({when:function(e){e&&fa(this);return e?e(b):this}},function(){return this},function(){return{state:"rejected",reason:b}});w(e,b);return e}function N(b){return g({when:function(){return b},
        get:function(e){return b[e]},set:function(e,c){b[e]=c},"delete":function(e){delete b[e]},post:function(e,c){return null===e||void 0===e?b.apply(void 0,c):b[e].apply(b,c)},apply:function(e,c){return b.apply(e,c)},keys:function(){return E(b)}},void 0,function(){return{state:"fulfilled",value:b}})}function da(b){var e=u();c.nextTick(function(){try{b.then(e.resolve,e.reject,e.notify)}catch(l){e.reject(l)}});return e.promise}function T(b,e,l){return c(b).spread(e,l)}function Y(b,e,l){return c(b).dispatch(e,
        l)}function M(b){return R(b,function(b){var e=0,c=u();oa(b,function(l,f,g){var r;I(f)&&"fulfilled"===(r=f.inspect()).state?b[g]=r.value:(++e,R(f,function(l){b[g]=l;0===--e&&c.resolve(b)},c.reject,function(b){c.notify({index:g,value:b})}))},void 0);0===e&&c.resolve(b);return c.promise})}function F(b){if(0===b.length)return c.resolve();var e=c.defer(),l=0;oa(b,function(c,f,g){c=b[g];l++;R(c,function(b){e.resolve(b)},function(b){l--;0===l&&(b=b||Error(""+b),b.message="Q can't get fulfillment value from any promise, all promises were rejected. Last error message: "+
        b.message,e.reject(b))},function(b){e.notify({index:g,value:b})})},void 0);return e.promise}function O(b){return R(b,function(b){b=Aa(b,c);return R(M(Aa(b,function(b){return R(b,Ea,Ea)})),function(){return b})})}var ba=!1;try{throw Error();}catch(b){ba=!!b.stack}var ca=C(),na,Ea=function(){},ha=function(){function b(){for(var b,l;c.next;){c=c.next;b=c.task;c.task=void 0;if(l=c.domain)c.domain=void 0,l.enter();e(b,l)}for(;p.length;)b=p.pop(),e(b);g=!1}function e(e,c){try{e()}catch(v){if(m)throw c&&
    c.exit(),setTimeout(b,0),c&&c.enter(),v;setTimeout(function(){throw v;},0)}c&&c.exit()}var c={task:void 0,next:null},f=c,g=!1,k=void 0,m=!1,p=[];ha=function(b){f=f.next={task:b,domain:m&&process.domain,next:null};g||(g=!0,k())};if("object"===typeof process&&"[object process]"===process.toString()&&process.nextTick)m=!0,k=function(){process.nextTick(b)};else if("function"===typeof setImmediate)k="undefined"!==typeof window?setImmediate.bind(window,b):function(){setImmediate(b)};else if("undefined"!==
        typeof MessageChannel){var u=new MessageChannel;u.port1.onmessage=function(){k=n;u.port1.onmessage=b;b()};var n=function(){u.port2.postMessage(0)};k=function(){setTimeout(b,0);n()}}else k=function(){setTimeout(b,0)};ha.runAfter=function(b){p.push(b);g||(g=!0,k())};return ha}(),m=Function.call,z=f(Array.prototype.slice),oa=f(Array.prototype.reduce||function(b,e){var c=0,f=this.length;if(1===arguments.length){do{if(c in this){e=this[c++];break}if(++c>=f)throw new TypeError;}while(1)}for(;c<f;c++)c in
    this&&(e=b(e,this[c],c));return e}),qa=f(Array.prototype.indexOf||function(b){for(var e=0;e<this.length;e++)if(this[e]===b)return e;return-1}),Aa=f(Array.prototype.map||function(b,e){var c=this,f=[];oa(c,function(l,g,k){f.push(b.call(e,g,k,c))},void 0);return f}),k=Object.create||function(b){function e(){}e.prototype=b;return new e},Ja=Object.defineProperty||function(b,e,c){b[e]=c.value;return b},Xa=f(Object.prototype.hasOwnProperty),E=Object.keys||function(b){var e=[],c;for(c in b)Xa(b,c)&&e.push(c);
        return e},ra=f(Object.prototype.toString);var Ba="undefined"!==typeof ReturnValue?ReturnValue:function(b){this.value=b};c.resolve=c;c.nextTick=ha;c.longStackSupport=!1;var La=1;"object"===typeof process&&process&&process.env&&process.env.Q_DEBUG&&(c.longStackSupport=!0);c.defer=u;u.prototype.makeNodeResolver=function(){var b=this;return function(e,c){e?b.reject(e):2<arguments.length?b.resolve(z(arguments,1)):b.resolve(c)}};c.Promise=G;c.promise=G;G.race=n;G.all=M;G.reject=D;G.resolve=c;c.passByCopy=
        function(b){return b};g.prototype.passByCopy=function(){return this};c.join=function(b,e){return c(b).join(e)};g.prototype.join=function(b){return c([this,b]).spread(function(b,c){if(b===c)return b;throw Error("Q can't join: not the same: "+b+" "+c);})};c.race=n;g.prototype.race=function(){return this.then(c.race)};c.makePromise=g;g.prototype.toString=function(){return"[object Promise]"};g.prototype.then=function(b,e,f){function l(e){try{return"function"===typeof b?b(e):e}catch(ea){return D(ea)}}
        function g(b){if("function"===typeof e){p(b,k);try{return e(b)}catch(ea){return D(ea)}}return D(b)}var k=this,m=u(),n=!1;c.nextTick(function(){k.promiseDispatch(function(b){n||(n=!0,m.resolve(l(b)))},"when",[function(b){n||(n=!0,m.resolve(g(b)))}])});k.promiseDispatch(void 0,"when",[void 0,function(b){var e=!1;try{var l="function"===typeof f?f(b):b}catch(Fa){if(e=!0,c.onerror)c.onerror(Fa);else throw Fa;}e||m.notify(l)}]);return m.promise};c.tap=function(b,e){return c(b).tap(e)};g.prototype.tap=function(b){b=
        c(b);return this.then(function(e){return b.fcall(e).thenResolve(e)})};c.when=R;g.prototype.thenResolve=function(b){return this.then(function(){return b})};c.thenResolve=function(b,e){return c(b).thenResolve(e)};g.prototype.thenReject=function(b){return this.then(function(){throw b;})};c.thenReject=function(b,e){return c(b).thenReject(e)};c.nearer=ya;c.isPromise=I;c.isPromiseAlike=L;c.isPending=function(b){return I(b)&&"pending"===b.inspect().state};g.prototype.isPending=function(){return"pending"===
        this.inspect().state};c.isFulfilled=function(b){return!I(b)||"fulfilled"===b.inspect().state};g.prototype.isFulfilled=function(){return"fulfilled"===this.inspect().state};c.isRejected=function(b){return I(b)&&"rejected"===b.inspect().state};g.prototype.isRejected=function(){return"rejected"===this.inspect().state};var W=[],X=[],za=[],J=!0;c.resetUnhandledRejections=H;c.getUnhandledReasons=function(){return W.slice()};c.stopUnhandledRejectionTracking=function(){H();J=!1};H();c.reject=D;c.fulfill=N;
    c.master=function(b){return g({isDef:function(){}},function(e,c){return Y(b,e,c)},function(){return c(b).inspect()})};c.spread=T;g.prototype.spread=function(b,e){return this.all().then(function(e){return b.apply(void 0,e)},e)};c.async=function(b){return function(){function e(b,e){if("undefined"===typeof StopIteration){try{var l=f[b](e)}catch(pa){return D(pa)}return l.done?c(l.value):R(l.value,g,k)}try{l=f[b](e)}catch(pa){return l=pa,"[object StopIteration]"===ra(l)||l instanceof Ba?c(pa.value):D(pa)}return R(l,
        g,k)}var f=b.apply(this,arguments),g=e.bind(e,"next"),k=e.bind(e,"throw");return g()}};c.spawn=function(b){c.done(c.async(b)())};c["return"]=function(b){throw new Ba(b);};c.promised=function(b){return function(){return T([this,M(arguments)],function(e,c){return b.apply(e,c)})}};c.dispatch=Y;g.prototype.dispatch=function(b,e){var f=this,g=u();c.nextTick(function(){f.promiseDispatch(g.resolve,b,e)});return g.promise};c.get=function(b,e){return c(b).dispatch("get",[e])};g.prototype.get=function(b){return this.dispatch("get",
        [b])};c.set=function(b,e,f){return c(b).dispatch("set",[e,f])};g.prototype.set=function(b,e){return this.dispatch("set",[b,e])};c.del=c["delete"]=function(b,e){return c(b).dispatch("delete",[e])};g.prototype.del=g.prototype["delete"]=function(b){return this.dispatch("delete",[b])};c.mapply=c.post=function(b,e,f){return c(b).dispatch("post",[e,f])};g.prototype.mapply=g.prototype.post=function(b,e){return this.dispatch("post",[b,e])};c.send=c.mcall=c.invoke=function(b,e){return c(b).dispatch("post",
        [e,z(arguments,2)])};g.prototype.send=g.prototype.mcall=g.prototype.invoke=function(b){return this.dispatch("post",[b,z(arguments,1)])};c.fapply=function(b,e){return c(b).dispatch("apply",[void 0,e])};g.prototype.fapply=function(b){return this.dispatch("apply",[void 0,b])};c["try"]=c.fcall=function(b){return c(b).dispatch("apply",[void 0,z(arguments,1)])};g.prototype.fcall=function(){return this.dispatch("apply",[void 0,z(arguments)])};c.fbind=function(b){var e=c(b),f=z(arguments,1);return function(){return e.dispatch("apply",
        [this,f.concat(z(arguments))])}};g.prototype.fbind=function(){var b=this,e=z(arguments);return function(){return b.dispatch("apply",[this,e.concat(z(arguments))])}};c.keys=function(b){return c(b).dispatch("keys",[])};g.prototype.keys=function(){return this.dispatch("keys",[])};c.all=M;g.prototype.all=function(){return M(this)};c.any=F;g.prototype.any=function(){return F(this)};c.allResolved=function(b,e,c){return function(){"undefined"!==typeof console&&"function"===typeof console.warn&&console.warn(e+
        " is deprecated, use "+c+" instead.",Error("").stack);return b.apply(b,arguments)}}(O,"allResolved","allSettled");g.prototype.allResolved=function(){return O(this)};c.allSettled=function(b){return c(b).allSettled()};g.prototype.allSettled=function(){return this.then(function(b){return M(Aa(b,function(b){function e(){return b.inspect()}b=c(b);return b.then(e,e)}))})};c.fail=c["catch"]=function(b,e){return c(b).then(void 0,e)};g.prototype.fail=g.prototype["catch"]=function(b){return this.then(void 0,
        b)};c.progress=function(b,e){return c(b).then(void 0,void 0,e)};g.prototype.progress=function(b){return this.then(void 0,void 0,b)};c.fin=c["finally"]=function(b,e){return c(b)["finally"](e)};g.prototype.fin=g.prototype["finally"]=function(b){if(!b||"function"!==typeof b.apply)throw Error("Q can't apply finally callback");b=c(b);return this.then(function(e){return b.fcall().then(function(){return e})},function(e){return b.fcall().then(function(){throw e;})})};c.done=function(b,e,f,g){return c(b).done(e,
        f,g)};g.prototype.done=function(b,e,f){var g=function(b){c.nextTick(function(){p(b,l);if(c.onerror)c.onerror(b);else throw b;})},l=b||e||f?this.then(b,e,f):this;"object"===typeof process&&process&&process.domain&&(g=process.domain.bind(g));l.then(void 0,g)};c.timeout=function(b,e,f){return c(b).timeout(e,f)};g.prototype.timeout=function(b,e){var c=u(),f=setTimeout(function(){e&&"string"!==typeof e||(e=Error(e||"Timed out after "+b+" ms"),e.code="ETIMEDOUT");c.reject(e)},b);this.then(function(b){clearTimeout(f);
        c.resolve(b)},function(b){clearTimeout(f);c.reject(b)},c.notify);return c.promise};c.delay=function(b,e){void 0===e&&(e=b,b=void 0);return c(b).delay(e)};g.prototype.delay=function(b){return this.then(function(e){var c=u();setTimeout(function(){c.resolve(e)},b);return c.promise})};c.nfapply=function(b,e){return c(b).nfapply(e)};g.prototype.nfapply=function(b){var c=u();b=z(b);b.push(c.makeNodeResolver());this.fapply(b).fail(c.reject);return c.promise};c.nfcall=function(b){var e=z(arguments,1);return c(b).nfapply(e)};
    g.prototype.nfcall=function(){var b=z(arguments),c=u();b.push(c.makeNodeResolver());this.fapply(b).fail(c.reject);return c.promise};c.nfbind=c.denodeify=function(b){if(void 0===b)throw Error("Q can't wrap an undefined function");var e=z(arguments,1);return function(){var f=e.concat(z(arguments)),g=u();f.push(g.makeNodeResolver());c(b).fapply(f).fail(g.reject);return g.promise}};g.prototype.nfbind=g.prototype.denodeify=function(){var b=z(arguments);b.unshift(this);return c.denodeify.apply(void 0,b)};
    c.nbind=function(b,e){var f=z(arguments,2);return function(){var g=f.concat(z(arguments)),k=u();g.push(k.makeNodeResolver());c(function(){return b.apply(e,arguments)}).fapply(g).fail(k.reject);return k.promise}};g.prototype.nbind=function(){var b=z(arguments,0);b.unshift(this);return c.nbind.apply(void 0,b)};c.nmapply=c.npost=function(b,e,f){return c(b).npost(e,f)};g.prototype.nmapply=g.prototype.npost=function(b,c){var e=z(c||[]),f=u();e.push(f.makeNodeResolver());this.dispatch("post",[b,e]).fail(f.reject);
        return f.promise};c.nsend=c.nmcall=c.ninvoke=function(b,e){var f=z(arguments,2),g=u();f.push(g.makeNodeResolver());c(b).dispatch("post",[e,f]).fail(g.reject);return g.promise};g.prototype.nsend=g.prototype.nmcall=g.prototype.ninvoke=function(b){var c=z(arguments,1),f=u();c.push(f.makeNodeResolver());this.dispatch("post",[b,c]).fail(f.reject);return f.promise};c.nodeify=function(b,e){return c(b).nodeify(e)};g.prototype.nodeify=function(b){if(b)this.then(function(e){c.nextTick(function(){b(null,e)})},
        function(e){c.nextTick(function(){b(e)})});else return this};c.noConflict=function(){throw Error("Q.noConflict only works when Q is used as a global");};var Ka=C();return c});
(function(f,p){"object"===typeof exports&&"undefined"!==typeof module?module.exports=p():"function"===typeof define&&define.amd?define(p):f.moment=p()})(this,function(){function f(){return Ib.apply(null,arguments)}function p(a){return"[object Array]"===Object.prototype.toString.call(a)}function y(a){return a instanceof Date||"[object Date]"===Object.prototype.toString.call(a)}function C(a,d){var b=[],c;for(c=0;c<a.length;++c)b.push(d(a[c],c));return b}function c(a,d){return Object.prototype.hasOwnProperty.call(a,
    d)}function u(a,d){for(var b in d)c(d,b)&&(a[b]=d[b]);c(d,"toString")&&(a.toString=d.toString);c(d,"valueOf")&&(a.valueOf=d.valueOf);return a}function G(a,d,b,c){return Fa(a,d,b,c,!0).utc()}function n(a){null==a._pf&&(a._pf={empty:!1,unusedTokens:[],unusedInput:[],overflow:-2,charsLeftOver:0,nullInput:!1,invalidMonth:null,invalidFormat:!1,userInvalidated:!1,iso:!1});return a._pf}function g(a){if(null==a._isValid){var d=n(a);a._isValid=!isNaN(a._d.getTime())&&0>d.overflow&&!d.empty&&!d.invalidMonth&&
    !d.invalidWeekday&&!d.nullInput&&!d.invalidFormat&&!d.userInvalidated;a._strict&&(a._isValid=a._isValid&&0===d.charsLeftOver&&0===d.unusedTokens.length&&void 0===d.bigHour)}return a._isValid}function R(a){var d=G(NaN);null!=a?u(n(d),a):n(d).userInvalidated=!0;return d}function ya(a,d){var b;"undefined"!==typeof d._isAMomentObject&&(a._isAMomentObject=d._isAMomentObject);"undefined"!==typeof d._i&&(a._i=d._i);"undefined"!==typeof d._f&&(a._f=d._f);"undefined"!==typeof d._l&&(a._l=d._l);"undefined"!==
typeof d._strict&&(a._strict=d._strict);"undefined"!==typeof d._tzm&&(a._tzm=d._tzm);"undefined"!==typeof d._isUTC&&(a._isUTC=d._isUTC);"undefined"!==typeof d._offset&&(a._offset=d._offset);"undefined"!==typeof d._pf&&(a._pf=n(d));"undefined"!==typeof d._locale&&(a._locale=d._locale);if(0<Ya.length)for(b in Ya){var c=Ya[b];var e=d[c];"undefined"!==typeof e&&(a[c]=e)}return a}function I(a){ya(this,a);this._d=new Date(null!=a._d?a._d.getTime():NaN);!1===Za&&(Za=!0,f.updateOffset(this),Za=!1)}function L(a){return a instanceof
    I||null!=a&&null!=a._isAMomentObject}function H(a){return 0>a?Math.ceil(a):Math.floor(a)}function w(a){a=+a;var d=0;0!==a&&isFinite(a)&&(d=H(a));return d}function fa(a,d,b){var x=Math.min(a.length,d.length),c=Math.abs(a.length-d.length),e=0,f;for(f=0;f<x;f++)(b&&a[f]!==d[f]||!b&&w(a[f])!==w(d[f]))&&e++;return e+c}function D(){}function N(a){return a?a.toLowerCase().replace("_","-"):a}function da(a){var d=null;if(!sa[a]&&"undefined"!==typeof module&&module&&module.exports)try{d=Ma._abbr,require("./locale/"+
    a),T(d)}catch(x){}return sa[a]}function T(a,d){var b;a&&(b="undefined"===typeof d?M(a):Y(a,d))&&(Ma=b);return Ma._abbr}function Y(a,d){if(null!==d)return d.abbr=a,sa[a]=sa[a]||new D,sa[a].set(d),T(a),sa[a];delete sa[a];return null}function M(a){var d;a&&a._locale&&a._locale._abbr&&(a=a._locale._abbr);if(!a)return Ma;if(!p(a)){if(d=da(a))return d;a=[a]}a:{d=0;for(var b,c,e,f;d<a.length;){f=N(a[d]).split("-");b=f.length;for(c=(c=N(a[d+1]))?c.split("-"):null;0<b;){if(e=da(f.slice(0,b).join("-"))){a=
    e;break a}if(c&&c.length>=b&&fa(f,c,!0)>=b-1)break;b--}d++}a=null}return a}function F(a,d){var b=a.toLowerCase();Ga[b]=Ga[b+"s"]=Ga[d]=a}function O(a){return"string"===typeof a?Ga[a]||Ga[a.toLowerCase()]:void 0}function ba(a){var d={},b,e;for(e in a)c(a,e)&&(b=O(e))&&(d[b]=a[e]);return d}function ca(a,d){return function(b){return null!=b?(this._d["set"+(this._isUTC?"UTC":"")+a](b),f.updateOffset(this,d),this):na(this,a)}}function na(a,d){return a._d["get"+(a._isUTC?"UTC":"")+d]()}function Ea(a,d){var b;
    if("object"===typeof a)for(b in a)this.set(b,a[b]);else if(a=O(a),"function"===typeof this[a])return this[a](d);return this}function ha(a,d,b){var x=""+Math.abs(a);return(0<=a?b?"+":"":"-")+Math.pow(10,Math.max(0,d-x.length)).toString().substr(1)+x}function m(a,d,b,c){var x=c;"string"===typeof c&&(x=function(){return this[c]()});a&&(Ca[a]=x);d&&(Ca[d[0]]=function(){return ha(x.apply(this,arguments),d[1],d[2])});b&&(Ca[b]=function(){return this.localeData().ordinal(x.apply(this,arguments),a)})}function z(a){return a.match(/\[[\s\S]/)?
    a.replace(/^\[|\]$/g,""):a.replace(/\\/g,"")}function oa(a){var d=a.match(kb),b;var c=0;for(b=d.length;c<b;c++)d[c]=Ca[d[c]]?Ca[d[c]]:z(d[c]);return function(x){var e="";for(c=0;c<b;c++)e+=d[c]instanceof Function?d[c].call(x,a):d[c];return e}}function qa(a,d){if(!a.isValid())return a.localeData().invalidDate();d=Aa(d,a.localeData());$a[d]=$a[d]||oa(d);return $a[d](a)}function Aa(a,d){function b(a){return d.longDateFormat(a)||a}var c=5;for(Na.lastIndex=0;0<=c&&Na.test(a);)a=a.replace(Na,b),Na.lastIndex=
    0,--c;return a}function k(a,d,b){ab[a]="function"===typeof d&&"[object Function]"===Object.prototype.toString.call(d)?d:function(a){return a&&b?b:d}}function Ja(a,d){return c(ab,a)?ab[a](d._strict,d._locale):new RegExp(Xa(a))}function Xa(a){return a.replace("\\","").replace(/\\(\[)|\\(\])|\[([^\]\[]*)\]|\\(.)/g,function(a,b,c,e,f){return b||c||e||f}).replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")}function E(a,d){var b,c=d;"string"===typeof a&&(a=[a]);"number"===typeof d&&(c=function(a,b){b[d]=w(a)});for(b=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               0;b<a.length;b++)bb[a[b]]=c}function ra(a,d){E(a,function(a,b,c,e){c._w=c._w||{};d(a,c._w,c,e)})}function Ba(a,d){return(new Date(Date.UTC(a,d+1,0))).getUTCDate()}function La(a,d){if("string"===typeof d&&(d=a.localeData().monthsParse(d),"number"!==typeof d))return a;var b=Math.min(a.date(),Ba(a.year(),d));a._d["set"+(a._isUTC?"UTC":"")+"Month"](d,b);return a}function W(a){return null!=a?(La(this,a),f.updateOffset(this,!0),this):na(this,"Month")}function X(a){var d;(d=a._a)&&-2===n(a).overflow&&(d=
    0>d[Z]||11<d[Z]?Z:1>d[U]||d[U]>Ba(d[V],d[Z])?U:0>d[P]||24<d[P]||24===d[P]&&(0!==d[ta]||0!==d[ua]||0!==d[va])?P:0>d[ta]||59<d[ta]?ta:0>d[ua]||59<d[ua]?ua:0>d[va]||999<d[va]?va:-1,n(a)._overflowDayOfYear&&(d<V||d>U)&&(d=U),n(a).overflow=d);return a}function za(a){!1===f.suppressDeprecationWarnings&&"undefined"!==typeof console&&console.warn&&console.warn("Deprecation warning: "+a)}function J(a,d){var b=!0;return u(function(){b&&(za(a+"\n"+Error().stack),b=!1);return d.apply(this,arguments)},d)}function Ka(a){var d,
    b=a._i,c=Jb.exec(b);if(c){n(a).iso=!0;var e=0;for(d=cb.length;e<d;e++)if(cb[e][1].exec(b)){a._f=cb[e][0];break}e=0;for(d=db.length;e<d;e++)if(db[e][1].exec(b)){a._f+=(c[6]||" ")+db[e][0];break}b.match(Oa)&&(a._f+="Z");Wa(a)}else a._isValid=!1}function b(a){var d=Kb.exec(a._i);null!==d?a._d=new Date(+d[1]):(Ka(a),!1===a._isValid&&(delete a._isValid,f.createFromInputFallback(a)))}function e(a,d,b,c,e,f,g){d=new Date(a,d,b,c,e,f,g);1970>a&&d.setFullYear(a);return d}function l(a){var d=new Date(Date.UTC.apply(null,
    arguments));1970>a&&d.setUTCFullYear(a);return d}function r(a){return 0===a%4&&0!==a%100||0===a%400}function ma(a,d,b){d=b-d;b-=a.day();b>d&&(b-=7);b<d-7&&(b+=7);a=v(a).add(b,"d");return{week:Math.ceil(a.dayOfYear()/7),year:a.year()}}function K(a,d,b){return null!=a?a:null!=d?d:b}function B(a){var d=[];if(!a._d){var b=new Date;b=a._useUTC?[b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate()]:[b.getFullYear(),b.getMonth(),b.getDate()];if(a._w&&null==a._a[U]&&null==a._a[Z]){var c=a._w;if(null!=c.GG||
    null!=c.W||null!=c.E){var f=1;var g=4;var h=K(c.GG,a._a[V],ma(v(),1,4).year);var k=K(c.W,1);c=K(c.E,1)}else f=a._locale._week.dow,g=a._locale._week.doy,h=K(c.gg,a._a[V],ma(v(),f,g).year),k=K(c.w,1),null!=c.d?(c=c.d,c<f&&++k):c=null!=c.e?c.e+f:f;g=6+f-g;var m=l(h,0,1+g).getUTCDay();m<f&&(m+=7);f=1+g+7*(k-1)-m+(null!=c?1*c:f);g=0<f?h:h-1;h=0<f?f:(r(h-1)?366:365)+f;a._a[V]=g;a._dayOfYear=h}a._dayOfYear&&(h=K(a._a[V],b[V]),a._dayOfYear>(r(h)?366:365)&&(n(a)._overflowDayOfYear=!0),h=l(h,0,a._dayOfYear),
    a._a[Z]=h.getUTCMonth(),a._a[U]=h.getUTCDate());for(h=0;3>h&&null==a._a[h];++h)a._a[h]=d[h]=b[h];for(;7>h;h++)a._a[h]=d[h]=null==a._a[h]?2===h?1:0:a._a[h];24===a._a[P]&&0===a._a[ta]&&0===a._a[ua]&&0===a._a[va]&&(a._nextDay=!0,a._a[P]=0);a._d=(a._useUTC?l:e).apply(null,d);null!=a._tzm&&a._d.setUTCMinutes(a._d.getUTCMinutes()-a._tzm);a._nextDay&&(a._a[P]=24)}}function Wa(a){if(a._f===f.ISO_8601)Ka(a);else{a._a=[];n(a).empty=!0;var d=""+a._i,b,e,g=d.length,h=0;var k=Aa(a._f,a._locale).match(kb)||[];
    for(b=0;b<k.length;b++){var l=k[b];if(e=(d.match(Ja(l,a))||[])[0]){var m=d.substr(0,d.indexOf(e));0<m.length&&n(a).unusedInput.push(m);d=d.slice(d.indexOf(e)+e.length);h+=e.length}if(Ca[l]){if(e?n(a).empty=!1:n(a).unusedTokens.push(l),m=a,null!=e&&c(bb,l))bb[l](e,m._a,m,l)}else a._strict&&!e&&n(a).unusedTokens.push(l)}n(a).charsLeftOver=g-h;0<d.length&&n(a).unusedInput.push(d);!0===n(a).bigHour&&12>=a._a[P]&&0<a._a[P]&&(n(a).bigHour=void 0);d=a._a;b=P;g=a._locale;k=a._a[P];h=a._meridiem;null!=h&&
    (null!=g.meridiemHour?k=g.meridiemHour(k,h):null!=g.isPM&&((g=g.isPM(h))&&12>k&&(k+=12),g||12!==k||(k=0)));d[b]=k;B(a);X(a)}}function pa(a){if(!a._d){var d=ba(a._i);a._a=[d.year,d.month,d.day||d.date,d.hour,d.minute,d.second,d.millisecond];B(a)}}function ea(a){var d=a._i,b=a._f;a._locale=a._locale||M(a._l);if(null===d||void 0===b&&""===d)return R({nullInput:!0});"string"===typeof d&&(a._i=d=a._locale.preparse(d));if(L(d))return new I(X(d));if(p(b))if(0===a._f.length)n(a).invalidFormat=!0,a._d=new Date(NaN);
else{for(d=0;d<a._f.length;d++){b=0;var c=ya({},a);null!=a._useUTC&&(c._useUTC=a._useUTC);c._f=a._f[d];Wa(c);if(g(c)&&(b+=n(c).charsLeftOver,b+=10*n(c).unusedTokens.length,n(c).score=b,null==e||b<e)){var e=b;var f=c}}u(a,f||c)}else b?Wa(a):y(d)?a._d=d:Hb(a);return a}function Hb(a){var d=a._i;void 0===d?a._d=new Date:y(d)?a._d=new Date(+d):"string"===typeof d?b(a):p(d)?(a._a=C(d.slice(0),function(a){return parseInt(a,10)}),B(a)):"object"===typeof d?pa(a):"number"===typeof d?a._d=new Date(d):f.createFromInputFallback(a)}
    function Fa(a,d,b,c,e){var x={};"boolean"===typeof b&&(c=b,b=void 0);x._isAMomentObject=!0;x._useUTC=x._isUTC=e;x._l=b;x._i=a;x._f=d;x._strict=c;a=new I(X(ea(x)));a._nextDay&&(a.add(1,"d"),a._nextDay=void 0);return a}function v(a,d,b,c){return Fa(a,d,b,c,!1)}function lb(a,d){var b;1===d.length&&p(d[0])&&(d=d[0]);if(!d.length)return v();var c=d[0];for(b=1;b<d.length;++b)if(!d[b].isValid()||d[b][a](c))c=d[b];return c}function Pa(a){a=ba(a);var b=a.year||0,c=a.quarter||0,e=a.month||0,f=a.week||0,g=a.day||
        0;this._milliseconds=+(a.millisecond||0)+1E3*(a.second||0)+6E4*(a.minute||0)+36E5*(a.hour||0);this._days=+g+7*f;this._months=+e+3*c+12*b;this._data={};this._locale=M();this._bubble()}function eb(a){return a instanceof Pa}function mb(a,b){m(a,0,0,function(){var a=this.utcOffset(),d="+";0>a&&(a=-a,d="-");return d+ha(~~(a/60),2)+b+ha(~~a%60,2)})}function fb(a){a=(a||"").match(Oa)||[];a=((a[a.length-1]||[])+"").match(Lb)||["-",0,0];var b=+(60*a[1])+w(a[2]);return"+"===a[0]?b:-b}function gb(a,b){if(b._isUTC){var d=
        b.clone();var c=(L(a)||y(a)?+a:+v(a))-+d;d._d.setTime(+d._d+c);f.updateOffset(d,!1);return d}return v(a).local()}function nb(){return this._isUTC&&0===this._offset}function ia(a,b){var d=a,e;eb(a)?d={ms:a._milliseconds,d:a._days,M:a._months}:"number"===typeof a?(d={},b?d[b]=a:d.milliseconds=a):(e=Mb.exec(a))?(d="-"===e[1]?-1:1,d={y:0,d:w(e[U])*d,h:w(e[P])*d,m:w(e[ta])*d,s:w(e[ua])*d,ms:w(e[va])*d}):(e=Nb.exec(a))?(d="-"===e[1]?-1:1,d={y:wa(e[2],d),M:wa(e[3],d),d:wa(e[4],d),h:wa(e[5],d),m:wa(e[6],
        d),s:wa(e[7],d),w:wa(e[8],d)}):null==d?d={}:"object"===typeof d&&("from"in d||"to"in d)&&(e=v(d.from),d=v(d.to),d=gb(d,e),e.isBefore(d)?d=ob(e,d):(d=ob(d,e),d.milliseconds=-d.milliseconds,d.months=-d.months),e=d,d={},d.ms=e.milliseconds,d.M=e.months);d=new Pa(d);eb(a)&&c(a,"_locale")&&(d._locale=a._locale);return d}function wa(a,d){var b=a&&parseFloat(a.replace(",","."));return(isNaN(b)?0:b)*d}function ob(a,d){var b={milliseconds:0,months:0};b.months=d.month()-a.month()+12*(d.year()-a.year());a.clone().add(b.months,
        "M").isAfter(d)&&--b.months;b.milliseconds=+d-+a.clone().add(b.months,"M");return b}function pb(a,d){return function(b,c){if(null!==c&&!isNaN(+c)){qb[d]||(za("moment()."+d+"(period, number) is deprecated. Please use moment()."+d+"(number, period)."),qb[d]=!0);var e=b;b=c;c=e}e=ia("string"===typeof b?+b:b,c);rb(this,e,a);return this}}function rb(a,d,b,c){var e=d._milliseconds,x=d._days;d=d._months;c=null==c?!0:c;e&&a._d.setTime(+a._d+e*b);x&&(e=na(a,"Date")+x*b,a._d["set"+(a._isUTC?"UTC":"")+"Date"](e));
        d&&La(a,na(a,"Month")+d*b);c&&f.updateOffset(a,x||d)}function sb(){var a=this.clone().utc();return 0<a.year()&&9999>=a.year()?"function"===typeof Date.prototype.toISOString?this.toDate().toISOString():qa(a,"YYYY-MM-DD[T]HH:mm:ss.SSS[Z]"):qa(a,"YYYYYY-MM-DD[T]HH:mm:ss.SSS[Z]")}function tb(a){if(void 0===a)return this._locale._abbr;a=M(a);null!=a&&(this._locale=a);return this}function ub(){return this._locale}function Qa(a,d){m(0,[a,a.length],0,d)}function vb(a,d,b){return ma(v([a,11,31+d-b]),d,b).week}
    function wb(a,d){m(a,0,0,function(){return this.localeData().meridiem(this.hours(),this.minutes(),d)})}function xb(a,d){return d._meridiemParse}function Ob(a,d){d[va]=w(1E3*("0."+a))}function yb(a){return a}function zb(a,d,b,c){var e=M();d=G().set(c,d);return e[b](d,a)}function Ha(a,d,b,c,e){"number"===typeof a&&(d=a,a=void 0);a=a||"";if(null!=d)return zb(a,d,b,e);var f=[];for(d=0;d<c;d++)f[d]=zb(a,d,b,e);return f}function Ab(a,d,b,c){d=ia(d,b);a._milliseconds+=c*d._milliseconds;a._days+=c*d._days;
        a._months+=c*d._months;return a._bubble()}function Bb(a){return 0>a?Math.floor(a):Math.ceil(a)}function ja(a){return function(){return this.as(a)}}function xa(a){return function(){return this._data[a]}}function Pb(a,b,c,e,f){return f.relativeTime(b||1,!!c,a,e)}function Ra(){var a=hb(this._milliseconds)/1E3,b=hb(this._days),c=hb(this._months);var e=H(a/60);var f=H(e/60);a%=60;e%=60;var g=H(c/12);c%=12;var h=this.asSeconds();return h?(0>h?"-":"")+"P"+(g?g+"Y":"")+(c?c+"M":"")+(b?b+"D":"")+(f||e||a?
        "T":"")+(f?f+"H":"")+(e?e+"M":"")+(a?a+"S":""):"P0D"}var Ya=f.momentProperties=[],Za=!1,sa={},Ma,Ga={},kb=/(\[[^\[]*\])|(\\)?(Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|Q|YYYYYY|YYYYY|YYYY|YY|gg(ggg?)?|GG(GGG?)?|e|E|a|A|hh?|HH?|mm?|ss?|S{1,9}|x|X|zz?|ZZ?|.)/g,Na=/(\[[^\[]*\])|(\\)?(LTS|LT|LL?L?L?|l{1,4})/g,$a={},Ca={},Cb=/\d/,S=/\d\d/,Db=/\d{3}/,ib=/\d{4}/,Sa=/[+-]?\d{6}/,A=/\d\d?/,Ta=/\d{1,3}/,jb=/\d{1,4}/,Ua=/[+-]?\d{1,6}/,Qb=/\d+/,Va=/[+-]?\d+/,Oa=/Z|[+-]\d\d:?\d\d/gi,Ia=/[0-9]*['a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF\/]+(\s*?[\u0600-\u06FF]+){1,2}/i,
        ab={},bb={},V=0,Z=1,U=2,P=3,ta=4,ua=5,va=6;m("M",["MM",2],"Mo",function(){return this.month()+1});m("MMM",0,0,function(a){return this.localeData().monthsShort(this,a)});m("MMMM",0,0,function(a){return this.localeData().months(this,a)});F("month","M");k("M",A);k("MM",A,S);k("MMM",Ia);k("MMMM",Ia);E(["M","MM"],function(a,b){b[Z]=w(a)-1});E(["MMM","MMMM"],function(a,b,c,e){e=c._locale.monthsParse(a,e,c._strict);null!=e?b[Z]=e:n(c).invalidMonth=a});var qb={};f.suppressDeprecationWarnings=!1;var Jb=/^\s*(?:[+-]\d{6}|\d{4})-(?:(\d\d-\d\d)|(W\d\d$)|(W\d\d-\d)|(\d\d\d))((T| )(\d\d(:\d\d(:\d\d(\.\d+)?)?)?)?([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/,
        cb=[["YYYYYY-MM-DD",/[+-]\d{6}-\d{2}-\d{2}/],["YYYY-MM-DD",/\d{4}-\d{2}-\d{2}/],["GGGG-[W]WW-E",/\d{4}-W\d{2}-\d/],["GGGG-[W]WW",/\d{4}-W\d{2}/],["YYYY-DDD",/\d{4}-\d{3}/]],db=[["HH:mm:ss.SSSS",/(T| )\d\d:\d\d:\d\d\.\d+/],["HH:mm:ss",/(T| )\d\d:\d\d:\d\d/],["HH:mm",/(T| )\d\d:\d\d/],["HH",/(T| )\d\d/]],Kb=/^\/?Date\((\-?\d+)/i;f.createFromInputFallback=J("moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.",
        function(a){a._d=new Date(a._i+(a._useUTC?" UTC":""))});m(0,["YY",2],0,function(){return this.year()%100});m(0,["YYYY",4],0,"year");m(0,["YYYYY",5],0,"year");m(0,["YYYYYY",6,!0],0,"year");F("year","y");k("Y",Va);k("YY",A,S);k("YYYY",jb,ib);k("YYYYY",Ua,Sa);k("YYYYYY",Ua,Sa);E(["YYYYY","YYYYYY"],V);E("YYYY",function(a,b){b[V]=2===a.length?f.parseTwoDigitYear(a):w(a)});E("YY",function(a,b){b[V]=f.parseTwoDigitYear(a)});f.parseTwoDigitYear=function(a){return w(a)+(68<w(a)?1900:2E3)};var Eb=ca("FullYear",
        !1);m("w",["ww",2],"wo","week");m("W",["WW",2],"Wo","isoWeek");F("week","w");F("isoWeek","W");k("w",A);k("ww",A,S);k("W",A);k("WW",A,S);ra(["w","ww","W","WW"],function(a,b,c,e){b[e.substr(0,1)]=w(a)});m("DDD",["DDDD",3],"DDDo","dayOfYear");F("dayOfYear","DDD");k("DDD",Ta);k("DDDD",Db);E(["DDD","DDDD"],function(a,b,c){c._dayOfYear=w(a)});f.ISO_8601=function(){};var Rb=J("moment().min is deprecated, use moment.min instead. https://github.com/moment/moment/issues/1548",function(){var a=v.apply(null,
        arguments);return a<this?this:a}),Sb=J("moment().max is deprecated, use moment.max instead. https://github.com/moment/moment/issues/1548",function(){var a=v.apply(null,arguments);return a>this?this:a});mb("Z",":");mb("ZZ","");k("Z",Oa);k("ZZ",Oa);E(["Z","ZZ"],function(a,b,c){c._useUTC=!0;c._tzm=fb(a)});var Lb=/([\+\-]|\d\d)/gi;f.updateOffset=function(){};var Mb=/(\-)?(?:(\d*)\.)?(\d+)\:(\d+)(?:\:(\d+)\.?(\d{3})?)?/,Nb=/^(-)?P(?:(?:([0-9,.]*)Y)?(?:([0-9,.]*)M)?(?:([0-9,.]*)D)?(?:T(?:([0-9,.]*)H)?(?:([0-9,.]*)M)?(?:([0-9,.]*)S)?)?|([0-9,.]*)W)$/;
    ia.fn=Pa.prototype;var Tb=pb(1,"add"),Ub=pb(-1,"subtract");f.defaultFormat="YYYY-MM-DDTHH:mm:ssZ";var Fb=J("moment().lang() is deprecated. Instead, use moment().localeData() to get the language configuration. Use moment().locale() to change languages.",function(a){return void 0===a?this.localeData():this.locale(a)});m(0,["gg",2],0,function(){return this.weekYear()%100});m(0,["GG",2],0,function(){return this.isoWeekYear()%100});Qa("gggg","weekYear");Qa("ggggg","weekYear");Qa("GGGG","isoWeekYear");
    Qa("GGGGG","isoWeekYear");F("weekYear","gg");F("isoWeekYear","GG");k("G",Va);k("g",Va);k("GG",A,S);k("gg",A,S);k("GGGG",jb,ib);k("gggg",jb,ib);k("GGGGG",Ua,Sa);k("ggggg",Ua,Sa);ra(["gggg","ggggg","GGGG","GGGGG"],function(a,b,c,e){b[e.substr(0,2)]=w(a)});ra(["gg","GG"],function(a,b,c,e){b[e]=f.parseTwoDigitYear(a)});m("Q",0,0,"quarter");F("quarter","Q");k("Q",Cb);E("Q",function(a,b){b[Z]=3*(w(a)-1)});m("D",["DD",2],"Do","date");F("date","D");k("D",A);k("DD",A,S);k("Do",function(a,b){return a?b._ordinalParse:
        b._ordinalParseLenient});E(["D","DD"],U);E("Do",function(a,b){b[U]=w(a.match(A)[0],10)});var Gb=ca("Date",!0);m("d",0,"do","day");m("dd",0,0,function(a){return this.localeData().weekdaysMin(this,a)});m("ddd",0,0,function(a){return this.localeData().weekdaysShort(this,a)});m("dddd",0,0,function(a){return this.localeData().weekdays(this,a)});m("e",0,0,"weekday");m("E",0,0,"isoWeekday");F("day","d");F("weekday","e");F("isoWeekday","E");k("d",A);k("e",A);k("E",A);k("dd",Ia);k("ddd",Ia);k("dddd",Ia);ra(["dd",
        "ddd","dddd"],function(a,b,c){var d=c._locale.weekdaysParse(a);null!=d?b.d=d:n(c).invalidWeekday=a});ra(["d","e","E"],function(a,b,c,e){b[e]=w(a)});m("H",["HH",2],0,"hour");m("h",["hh",2],0,function(){return this.hours()%12||12});wb("a",!0);wb("A",!1);F("hour","h");k("a",xb);k("A",xb);k("H",A);k("h",A);k("HH",A,S);k("hh",A,S);E(["H","HH"],P);E(["a","A"],function(a,b,c){c._isPm=c._locale.isPM(a);c._meridiem=a});E(["h","hh"],function(a,b,c){b[P]=w(a);n(c).bigHour=!0});var Vb=ca("Hours",!0);m("m",["mm",
        2],0,"minute");F("minute","m");k("m",A);k("mm",A,S);E(["m","mm"],ta);var Wb=ca("Minutes",!1);m("s",["ss",2],0,"second");F("second","s");k("s",A);k("ss",A,S);E(["s","ss"],ua);var Xb=ca("Seconds",!1);m("S",0,0,function(){return~~(this.millisecond()/100)});m(0,["SS",2],0,function(){return~~(this.millisecond()/10)});m(0,["SSS",3],0,"millisecond");m(0,["SSSS",4],0,function(){return 10*this.millisecond()});m(0,["SSSSS",5],0,function(){return 100*this.millisecond()});m(0,["SSSSSS",6],0,function(){return 1E3*
        this.millisecond()});m(0,["SSSSSSS",7],0,function(){return 1E4*this.millisecond()});m(0,["SSSSSSSS",8],0,function(){return 1E5*this.millisecond()});m(0,["SSSSSSSSS",9],0,function(){return 1E6*this.millisecond()});F("millisecond","ms");k("S",Ta,Cb);k("SS",Ta,S);k("SSS",Ta,Db);var ka;for(ka="SSSS";9>=ka.length;ka+="S")k(ka,Qb);for(ka="S";9>=ka.length;ka+="S")E(ka,Ob);var Yb=ca("Milliseconds",!1);m("z",0,0,"zoneAbbr");m("zz",0,0,"zoneName");var h=I.prototype;h.add=Tb;h.calendar=function(a,b){var d=a||
        v(),c=gb(d,this).startOf("day");c=this.diff(c,"days",!0);c=-6>c?"sameElse":-1>c?"lastWeek":0>c?"lastDay":1>c?"sameDay":2>c?"nextDay":7>c?"nextWeek":"sameElse";return this.format(b&&b[c]||this.localeData().calendar(c,this,v(d)))};h.clone=function(){return new I(this)};h.diff=function(a,b,c){a=gb(a,this);var d=6E4*(a.utcOffset()-this.utcOffset());b=O(b);if("year"===b||"month"===b||"quarter"===b){d=12*(a.year()-this.year())+(a.month()-this.month());var e=this.clone().add(d,"months");if(0>a-e){var f=
        this.clone().add(d-1,"months");a=(a-e)/(e-f)}else f=this.clone().add(d+1,"months"),a=(a-e)/(f-e);a=-(d+a);"quarter"===b?a/=3:"year"===b&&(a/=12)}else a=this-a,a="second"===b?a/1E3:"minute"===b?a/6E4:"hour"===b?a/36E5:"day"===b?(a-d)/864E5:"week"===b?(a-d)/6048E5:a;return c?a:H(a)};h.endOf=function(a){a=O(a);return void 0===a||"millisecond"===a?this:this.startOf(a).add(1,"isoWeek"===a?"week":a).subtract(1,"ms")};h.format=function(a){a=qa(this,a||f.defaultFormat);return this.localeData().postformat(a)};
    h.from=function(a,b){return this.isValid()?ia({to:this,from:a}).locale(this.locale()).humanize(!b):this.localeData().invalidDate()};h.fromNow=function(a){return this.from(v(),a)};h.to=function(a,b){return this.isValid()?ia({from:this,to:a}).locale(this.locale()).humanize(!b):this.localeData().invalidDate()};h.toNow=function(a){return this.to(v(),a)};h.get=Ea;h.invalidAt=function(){return n(this).overflow};h.isAfter=function(a,b){b=O("undefined"!==typeof b?b:"millisecond");return"millisecond"===b?
        (a=L(a)?a:v(a),+this>+a):(L(a)?+a:+v(a))<+this.clone().startOf(b)};h.isBefore=function(a,b){b=O("undefined"!==typeof b?b:"millisecond");if("millisecond"===b)return a=L(a)?a:v(a),+this<+a;var d=L(a)?+a:+v(a);return+this.clone().endOf(b)<d};h.isBetween=function(a,b,c){return this.isAfter(a,c)&&this.isBefore(b,c)};h.isSame=function(a,b){b=O(b||"millisecond");if("millisecond"===b)return a=L(a)?a:v(a),+this===+a;var d=+v(a);return+this.clone().startOf(b)<=d&&d<=+this.clone().endOf(b)};h.isValid=function(){return g(this)};
    h.lang=Fb;h.locale=tb;h.localeData=ub;h.max=Sb;h.min=Rb;h.parsingFlags=function(){return u({},n(this))};h.set=Ea;h.startOf=function(a){a=O(a);switch(a){case "year":this.month(0);case "quarter":case "month":this.date(1);case "week":case "isoWeek":case "day":this.hours(0);case "hour":this.minutes(0);case "minute":this.seconds(0);case "second":this.milliseconds(0)}"week"===a&&this.weekday(0);"isoWeek"===a&&this.isoWeekday(1);"quarter"===a&&this.month(3*Math.floor(this.month()/3));return this};h.subtract=
        Ub;h.toArray=function(){return[this.year(),this.month(),this.date(),this.hour(),this.minute(),this.second(),this.millisecond()]};h.toObject=function(){return{years:this.year(),months:this.month(),date:this.date(),hours:this.hours(),minutes:this.minutes(),seconds:this.seconds(),milliseconds:this.milliseconds()}};h.toDate=function(){return this._offset?new Date(+this):this._d};h.toISOString=sb;h.toJSON=sb;h.toString=function(){return this.clone().locale("en").format("ddd MMM DD YYYY HH:mm:ss [GMT]ZZ")};
    h.unix=function(){return Math.floor(+this/1E3)};h.valueOf=function(){return+this._d-6E4*(this._offset||0)};h.year=Eb;h.isLeapYear=function(){return r(this.year())};h.weekYear=function(a){var b=ma(this,this.localeData()._week.dow,this.localeData()._week.doy).year;return null==a?b:this.add(a-b,"y")};h.isoWeekYear=function(a){var b=ma(this,1,4).year;return null==a?b:this.add(a-b,"y")};h.quarter=h.quarters=function(a){return null==a?Math.ceil((this.month()+1)/3):this.month(3*(a-1)+this.month()%3)};h.month=
        W;h.daysInMonth=function(){return Ba(this.year(),this.month())};h.week=h.weeks=function(a){var b=this.localeData().week(this);return null==a?b:this.add(7*(a-b),"d")};h.isoWeek=h.isoWeeks=function(a){var b=ma(this,1,4).week;return null==a?b:this.add(7*(a-b),"d")};h.weeksInYear=function(){var a=this.localeData()._week;return vb(this.year(),a.dow,a.doy)};h.isoWeeksInYear=function(){return vb(this.year(),1,4)};h.date=Gb;h.day=h.days=function(a){var b=this._isUTC?this._d.getUTCDay():this._d.getDay();if(null!=
        a){var c=this.localeData();"string"===typeof a&&(isNaN(a)?(a=c.weekdaysParse(a),a="number"===typeof a?a:null):a=parseInt(a,10));return this.add(a-b,"d")}return b};h.weekday=function(a){var b=(this.day()+7-this.localeData()._week.dow)%7;return null==a?b:this.add(a-b,"d")};h.isoWeekday=function(a){return null==a?this.day()||7:this.day(this.day()%7?a:a-7)};h.dayOfYear=function(a){var b=Math.round((this.clone().startOf("day")-this.clone().startOf("year"))/864E5)+1;return null==a?b:this.add(a-b,"d")};
    h.hour=h.hours=Vb;h.minute=h.minutes=Wb;h.second=h.seconds=Xb;h.millisecond=h.milliseconds=Yb;h.utcOffset=function(a,b){var d=this._offset||0,c;return null!=a?("string"===typeof a&&(a=fb(a)),16>Math.abs(a)&&(a*=60),!this._isUTC&&b&&(c=15*-Math.round(this._d.getTimezoneOffset()/15)),this._offset=a,this._isUTC=!0,null!=c&&this.add(c,"m"),d!==a&&(!b||this._changeInProgress?rb(this,ia(a-d,"m"),1,!1):this._changeInProgress||(this._changeInProgress=!0,f.updateOffset(this,!0),this._changeInProgress=null)),
        this):this._isUTC?d:15*-Math.round(this._d.getTimezoneOffset()/15)};h.utc=function(a){return this.utcOffset(0,a)};h.local=function(a){this._isUTC&&(this.utcOffset(0,a),this._isUTC=!1,a&&this.subtract(15*-Math.round(this._d.getTimezoneOffset()/15),"m"));return this};h.parseZone=function(){this._tzm?this.utcOffset(this._tzm):"string"===typeof this._i&&this.utcOffset(fb(this._i));return this};h.hasAlignedHourOffset=function(a){a=a?v(a).utcOffset():0;return 0===(this.utcOffset()-a)%60};h.isDST=function(){return this.utcOffset()>
        this.clone().month(0).utcOffset()||this.utcOffset()>this.clone().month(5).utcOffset()};h.isDSTShifted=function(){if("undefined"!==typeof this._isDSTShifted)return this._isDSTShifted;var a={};ya(a,this);a=ea(a);if(a._a){var b=a._isUTC?G(a._a):v(a._a);this._isDSTShifted=this.isValid()&&0<fa(a._a,b.toArray())}else this._isDSTShifted=!1;return this._isDSTShifted};h.isLocal=function(){return!this._isUTC};h.isUtcOffset=function(){return this._isUTC};h.isUtc=nb;h.isUTC=nb;h.zoneAbbr=function(){return this._isUTC?
        "UTC":""};h.zoneName=function(){return this._isUTC?"Coordinated Universal Time":""};h.dates=J("dates accessor is deprecated. Use date instead.",Gb);h.months=J("months accessor is deprecated. Use month instead",W);h.years=J("years accessor is deprecated. Use year instead",Eb);h.zone=J("moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779",function(a,b){return null!=a?("string"!==typeof a&&(a=-a),this.utcOffset(a,b),this):-this.utcOffset()});var q=
        D.prototype;q._calendar={sameDay:"[Today at] LT",nextDay:"[Tomorrow at] LT",nextWeek:"dddd [at] LT",lastDay:"[Yesterday at] LT",lastWeek:"[Last] dddd [at] LT",sameElse:"L"};q.calendar=function(a,b,c){a=this._calendar[a];return"function"===typeof a?a.call(b,c):a};q._longDateFormat={LTS:"h:mm:ss A",LT:"h:mm A",L:"MM/DD/YYYY",LL:"MMMM D, YYYY",LLL:"MMMM D, YYYY h:mm A",LLLL:"dddd, MMMM D, YYYY h:mm A"};q.longDateFormat=function(a){var b=this._longDateFormat[a],c=this._longDateFormat[a.toUpperCase()];
        if(b||!c)return b;this._longDateFormat[a]=c.replace(/MMMM|MM|DD|dddd/g,function(a){return a.slice(1)});return this._longDateFormat[a]};q._invalidDate="Invalid date";q.invalidDate=function(){return this._invalidDate};q._ordinal="%d";q.ordinal=function(a){return this._ordinal.replace("%d",a)};q._ordinalParse=/\d{1,2}/;q.preparse=yb;q.postformat=yb;q._relativeTime={future:"in %s",past:"%s ago",s:"a few seconds",m:"a minute",mm:"%d minutes",h:"an hour",hh:"%d hours",d:"a day",dd:"%d days",M:"a month",
        MM:"%d months",y:"a year",yy:"%d years"};q.relativeTime=function(a,b,c,e){var d=this._relativeTime[c];return"function"===typeof d?d(a,b,c,e):d.replace(/%d/i,a)};q.pastFuture=function(a,b){var d=this._relativeTime[0<a?"future":"past"];return"function"===typeof d?d(b):d.replace(/%s/i,b)};q.set=function(a){var b;for(b in a){var c=a[b];"function"===typeof c?this[b]=c:this["_"+b]=c}this._ordinalParseLenient=new RegExp(this._ordinalParse.source+"|"+/\d{1,2}/.source)};q.months=function(a){return this._months[a.month()]};
    q._months="January February March April May June July August September October November December".split(" ");q.monthsShort=function(a){return this._monthsShort[a.month()]};q._monthsShort="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");q.monthsParse=function(a,b,c){var d;this._monthsParse||(this._monthsParse=[],this._longMonthsParse=[],this._shortMonthsParse=[]);for(d=0;12>d;d++){var e=G([2E3,d]);c&&!this._longMonthsParse[d]&&(this._longMonthsParse[d]=new RegExp("^"+this.months(e,"").replace(".",
        "")+"$","i"),this._shortMonthsParse[d]=new RegExp("^"+this.monthsShort(e,"").replace(".","")+"$","i"));c||this._monthsParse[d]||(e="^"+this.months(e,"")+"|^"+this.monthsShort(e,""),this._monthsParse[d]=new RegExp(e.replace(".",""),"i"));if(c&&"MMMM"===b&&this._longMonthsParse[d].test(a)||c&&"MMM"===b&&this._shortMonthsParse[d].test(a)||!c&&this._monthsParse[d].test(a))return d}};q.week=function(a){return ma(a,this._week.dow,this._week.doy).week};q._week={dow:0,doy:6};q.firstDayOfYear=function(){return this._week.doy};
    q.firstDayOfWeek=function(){return this._week.dow};q.weekdays=function(a){return this._weekdays[a.day()]};q._weekdays="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");q.weekdaysMin=function(a){return this._weekdaysMin[a.day()]};q._weekdaysMin="Su Mo Tu We Th Fr Sa".split(" ");q.weekdaysShort=function(a){return this._weekdaysShort[a.day()]};q._weekdaysShort="Sun Mon Tue Wed Thu Fri Sat".split(" ");q.weekdaysParse=function(a){var b;this._weekdaysParse=this._weekdaysParse||[];for(b=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               0;7>b;b++){if(!this._weekdaysParse[b]){var c=v([2E3,1]).day(b);c="^"+this.weekdays(c,"")+"|^"+this.weekdaysShort(c,"")+"|^"+this.weekdaysMin(c,"");this._weekdaysParse[b]=new RegExp(c.replace(".",""),"i")}if(this._weekdaysParse[b].test(a))return b}};q.isPM=function(a){return"p"===(a+"").toLowerCase().charAt(0)};q._meridiemParse=/[ap]\.?m?\.?/i;q.meridiem=function(a,b,c){return 11<a?c?"pm":"PM":c?"am":"AM"};T("en",{ordinalParse:/\d{1,2}(th|st|nd|rd)/,ordinal:function(a){var b=a%10;b=1===w(a%100/10)?
        "th":1===b?"st":2===b?"nd":3===b?"rd":"th";return a+b}});f.lang=J("moment.lang is deprecated. Use moment.locale instead.",T);f.langData=J("moment.langData is deprecated. Use moment.localeData instead.",M);var aa=Math.abs,Zb=ja("ms"),$b=ja("s"),ac=ja("m"),bc=ja("h"),cc=ja("d"),dc=ja("w"),ec=ja("M"),fc=ja("y"),gc=xa("milliseconds"),hc=xa("seconds"),ic=xa("minutes"),jc=xa("hours"),kc=xa("days"),lc=xa("months"),mc=xa("years"),Da=Math.round,la={s:45,m:45,h:22,d:26,M:11},hb=Math.abs,t=Pa.prototype;t.abs=
        function(){var a=this._data;this._milliseconds=aa(this._milliseconds);this._days=aa(this._days);this._months=aa(this._months);a.milliseconds=aa(a.milliseconds);a.seconds=aa(a.seconds);a.minutes=aa(a.minutes);a.hours=aa(a.hours);a.months=aa(a.months);a.years=aa(a.years);return this};t.add=function(a,b){return Ab(this,a,b,1)};t.subtract=function(a,b){return Ab(this,a,b,-1)};t.as=function(a){var b=this._milliseconds;a=O(a);if("month"===a||"year"===a){var c=this._days+b/864E5;c=this._months+4800*c/146097;
        return"month"===a?c:c/12}c=this._days+Math.round(146097*this._months/4800);switch(a){case "week":return c/7+b/6048E5;case "day":return c+b/864E5;case "hour":return 24*c+b/36E5;case "minute":return 1440*c+b/6E4;case "second":return 86400*c+b/1E3;case "millisecond":return Math.floor(864E5*c)+b;default:throw Error("Unknown unit "+a);}};t.asMilliseconds=Zb;t.asSeconds=$b;t.asMinutes=ac;t.asHours=bc;t.asDays=cc;t.asWeeks=dc;t.asMonths=ec;t.asYears=fc;t.valueOf=function(){return this._milliseconds+864E5*
        this._days+this._months%12*2592E6+31536E6*w(this._months/12)};t._bubble=function(){var a=this._milliseconds,b=this._days,c=this._months,e=this._data;0<=a&&0<=b&&0<=c||0>=a&&0>=b&&0>=c||(a+=864E5*Bb(146097*c/4800+b),c=b=0);e.milliseconds=a%1E3;a=H(a/1E3);e.seconds=a%60;a=H(a/60);e.minutes=a%60;a=H(a/60);e.hours=a%24;b+=H(a/24);a=H(4800*b/146097);c+=a;b-=Bb(146097*a/4800);a=H(c/12);e.days=b;e.months=c%12;e.years=a;return this};t.get=function(a){a=O(a);return this[a+"s"]()};t.milliseconds=gc;t.seconds=
        hc;t.minutes=ic;t.hours=jc;t.days=kc;t.weeks=function(){return H(this.days()/7)};t.months=lc;t.years=mc;t.humanize=function(a){var b=this.localeData();var c=!a;var e=ia(this).abs(),f=Da(e.as("s")),g=Da(e.as("m")),h=Da(e.as("h")),k=Da(e.as("d")),l=Da(e.as("M"));e=Da(e.as("y"));f=f<la.s&&["s",f]||1===g&&["m"]||g<la.m&&["mm",g]||1===h&&["h"]||h<la.h&&["hh",h]||1===k&&["d"]||k<la.d&&["dd",k]||1===l&&["M"]||l<la.M&&["MM",l]||1===e&&["y"]||["yy",e];f[2]=c;f[3]=0<+this;f[4]=b;c=Pb.apply(null,f);a&&(c=b.pastFuture(+this,
        c));return b.postformat(c)};t.toISOString=Ra;t.toString=Ra;t.toJSON=Ra;t.locale=tb;t.localeData=ub;t.toIsoString=J("toIsoString() is deprecated. Please use toISOString() instead (notice the capitals)",Ra);t.lang=Fb;m("X",0,0,"unix");m("x",0,0,"valueOf");k("x",Va);k("X",/[+-]?\d+(\.\d{1,3})?/);E("X",function(a,b,c){c._d=new Date(1E3*parseFloat(a,10))});E("x",function(a,b,c){c._d=new Date(w(a))});f.version="2.10.6";var Ib=v;f.fn=h;f.min=function(){var a=[].slice.call(arguments,0);return lb("isBefore",
        a)};f.max=function(){var a=[].slice.call(arguments,0);return lb("isAfter",a)};f.utc=G;f.unix=function(a){return v(1E3*a)};f.months=function(a,b){return Ha(a,b,"months",12,"month")};f.isDate=y;f.locale=T;f.invalid=R;f.duration=ia;f.isMoment=L;f.weekdays=function(a,b){return Ha(a,b,"weekdays",7,"day")};f.parseZone=function(){return v.apply(null,arguments).parseZone()};f.localeData=M;f.isDuration=eb;f.monthsShort=function(a,b){return Ha(a,b,"monthsShort",12,"month")};f.weekdaysMin=function(a,b){return Ha(a,
        b,"weekdaysMin",7,"day")};f.defineLocale=Y;f.weekdaysShort=function(a,b){return Ha(a,b,"weekdaysShort",7,"day")};f.normalizeUnits=O;f.relativeTimeThreshold=function(a,b){if(void 0===la[a])return!1;if(void 0===b)return la[a];la[a]=b;return!0};return f});getUrls=function(f,p){this.getManifest(f).then(this.getSegmentsAndByteLengthFromManifest.bind(this)).then(function(f){p(f.urls)})["catch"](function(f){console.error(f)})};
getSegmentsAndByteLengthFromManifest=function(f){var p=this,y=[],C=[],c=$(f.find("MPD")[0]).attr("mediaPresentationDuration"),u=moment.duration(c).asMilliseconds(),G=0;console.info("MEDIA DURATION",u);f.find("AdaptationSet").each(function(c,f){try{var g=$(f),n=$(g.find("SegmentTemplate")[0]),I=n.attr("media"),L=n.attr("initialization"),H=Number(n.attr("duration"))/Number(n.attr("timescale"))*1E3,w=Math.ceil(u/H),fa=Number(n.attr("startNumber")),D={},N={startNumber:fa,fragments:[]},da=0,T=[],Y;g.find("Representation").each(function(c,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         f){var g=$(f),n=Number(g.attr("bandwidth"));g=g.attr("id");T.push(g);n>da&&(da=n);Y="("+T.map(p.escapeRegExp).join("|")+")";D.urlTemplate=L.replace("$RepresentationID$",g);D.matchingFileName=p.getFileName(L).replace("$RepresentationID$",g);D.matchingUrl=p.escapeRegExp(L).replace(p.escapeRegExp("$RepresentationID$"),Y);D.fragments=[{url:D.urlTemplate}];C.push(D.fragments[0].url);N.urlTemplate=I.replace("$RepresentationID$",g);N.matchingFileName=p.getFileName(I).replace("$RepresentationID$",g);N.matchingUrl=
    p.escapeRegExp(I).replace(p.escapeRegExp("$Number$"),"(\\d+)").replace(p.escapeRegExp("$RepresentationID$"),Y);c=fa;for(n=w+fa;c<n;++c)N.fragments.push({url:N.urlTemplate.replace("$Number$",c)}),C.push(N.urlTemplate.replace("$Number$",c));y.push(D,N)});G+=da}catch(M){}});G=Math.ceil(G*u/8/1E3*1.25+102400);console.info("SEGMENTS",y);return{segments:y,urls:C,byteLength:G}};getManifest=function(f){return this.xhrGet(f).then(function(f){return $($.parseXML(f))})["catch"](function(f){console.error("FAILED LOADING MANIFEST")})};
getLls=function(f){return Q(!f&&this.lls||this.requestLls(f))};requestLls=function(f){var p=this,y=this.getConfig("requestedStorageSize");return!f&&this.llsPromise||(this.llsPromise=(new LargeLocalStorage({size:y,name:this.getConfig("contentId")})).initialized.then(function(f){var c=f.getCapacity();console.info("INITIALIZED LLS WITH CAPACITY:",c,y);return c<y?Q.reject(f):f})["catch"](function(){p.llsPromise=null;p.sendNotification("userFsDenial");console.error("ERROR CREATING LLS. USER DENIAL.")}))};
getFileName=function(f){return f.split("/").pop()};readAttachment=function(f,p,y){var C=this;return this.getLls().then(function(c){return c.getAttachment(f,p).then(function(c){console.info("ATTACHMENT READ SUCCESSFULLY:",f+"/"+p,c);return c?C.readFile(c,y):Q.reject(c)})})};
xhrGet=function(f,p){var y=Q.defer(),C=new XMLHttpRequest;C.responseType=p||"text";C.open("GET",f,!0);C.onreadystatechange=function(){4===C.readyState&&(200<=C.status&&400>C.status?y.resolve(C.response):y.reject({status:C.status}))};C.onprogress=function(c){y.notify(c)};C.send("");return y.promise};escapeRegExp=function(f){return f.trim().replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")};